common/collect_data.yaml
common/output_files.yaml
templates/atomic_smoke_output.j2
tests/new-image-smoketest/main.yaml
vars/smoketest_vars.yaml

This adds a simple smoketest that assumes a new cloud image has been
released and there are no updates available.  It tests to verify that an
upgrade is not possible, as well as a rollback is not possible.
`common/collect_data.yaml`
- Clean up trailing whitespace
`common/output_files.yaml`
- Changed the RPM diff task to only run when the `upgraded_rpms` var
is defined
`templates/atomic_smoke_output.j2`
- Changed the template to only generate RPM diff content if the
`upgraded_atomic_version` variable is defined
`tests/new-image-smoketest/main.yaml`
- New playbook for cloud images
`tests/new-tree-smoketest/main.yaml`
- Changed to include the var file
`vars/smoketest_vars.yaml`
- Moved the vars from `group_vars/all` to a common file that can be
included

Add new image smoketest

---

common/scripts/check_downgrade.py
rhel/subscribe.yaml
tests/new-tree-smoketest/main.yaml
vars/smoketest_vars.yaml

This adds a Python script to check the recorded output of `atomic host
upgrade` for any packages that may have been downgraded as part of the
upgrade to a new tree.
Additionally, the variable used by the `subscribe` task was changed to
be more meaningful.

new-tree-smoketest: add pkg downgrade check

---

common/check_tmp_perms.yaml
tests/new-image-smoketest/main.yaml
tests/new-tree-smoketest/main.yaml

There is an old BZ ([1276775](https://bugzilla.redhat.com/show_bug.cgi?id=1276775)) that reported bad permissions on `/tmp`; this
change adds a check for bad permissions and bad ownership on `/tmp`.

Add check for wonky /tmp

---

common/ans_reboot.yaml

Previously we used `inventory_hostname` as an argument to the `wait_for`
module.  But this did not always work with hostnames that were only
defined in the `inventory` file.  Switching to using the IP address of
the host via `ansible_default_ipv4.address` allows the playbook to be
run with an `inventory` file or with an inventory argument on the
command line like:
`ansible-playbook -i "192.168.122.34," -u cloud-user tests/new-tree-smoektest/main.yaml`

ans_reboot: Make reboot more reliable

---

common/rpm_diffs.yaml

When running `diff` we only care if the return code is 1 (indicating a
difference between the two files), so all other return codes are
failures.

rpm_diffs: Changing how rpm diff fails

---

tests/new-image-smoketest/main.yaml
tests/new-tree-smoketest/main.yaml
vars/smoketest_vars.yaml
vars/subscription.yaml

This moves the definition of the `subscription_file` variable to a
separate var file, in the attempt to minimize the amount of variables to
include for future tests.

Change location of 'subscription_file' variable

---

common/compare_version.yaml
common/multiple_rollback.yaml
common/multiple_rollback_reboot.yaml
tests/multiple-rollback-reboot/README.md
tests/multiple-rollback-reboot/main.yaml
tests/multiple-rollback/README.md
tests/multiple-rollback/main.yaml

These tests perform multiple rollbacks on the host to verify that the
mechanism works correctly.  After each rollback, the results of
`rpm-ostree status` are inspected to make sure the expected deployment
is in the right place.
There are two versions of the test: one just does a number of rollbacks
and the other does a rollback/reboot combination.

Add multiple rollback tests

---

common/scripts/atomic_rollback_interrupt.sh
tests/rollback-interrupt/README.md
tests/rollback-interrupt/main.yaml

This change introduces a plabyook to test interrupting the `rpm-ostree
rollback` operation.  The operation can be interrupted one or multiple
times, controlled via the `iterations` variable that can be passed to
the playbook.

Playbook to test interrupting rollback operation

---

common/scripts/atomic_upgrade_interrupt.sh
tests/upgrade-interrupt/README.md
tests/upgrade-interrupt/main.yaml

It is possible to interrupt the upgrade process and have no negative
impact to the running system.  This playbook verifies that interrupting
the upgrade does not affect the running system or the ability to
complete an upgrade after the fact.

Playbook to test interrupting upgrade operation

---

common/ans_reboot.yaml

This reverts commit 9382b2e259cdb58fcb0621ed114fbb5e2d02ab6b.
In a cloud environment, it is possible that the system under test will
not have the interface with the external IP address explicitly listed in
the output of the likes of `ip address` or `ifconfig`.  This causes the
value of `ansible_default_ipv4.address` to be a non-routable address and
cannot be used reliably, unless the host running the Ansible playbooks
is also in the same cloud environment.
We will go back to using `inventory_hostname` and will have to work
around any issues that are encountered.

Revert "ans_reboot: Make reboot more reliable"

---

common/ans_reboot.yaml

I kept running into trouble with the reboot task when testing with local
VMs.  Sometimes the VM wouldn't be identified as having come down, other
times the VM wouldn't be identified as having come up.
After some experimenting, I settled on just waiting for the host to come
up after a short delay.

Change reboot task to just wait for host to come up

---

tests/new-tree-smoketest/README.md
tests/new-tree-smoketest/main.yaml

This change introduces the ability to perform the smoketest on a tree
that was delivered via `rpm-ostree rebase`.  In doing so, a number of
tags were introduced for some tasks in order to limit which delivery
mechanism can be used.
For example, when testing a new tree delivered via `rpm-ostree upgrade`,
the test should not run the `rpm-ostree rebase` command (and associated
tasks).  This is accomplished through the use of `--skip-tags
rpm_ostree_rebase` when running the playbook.  A similar exclusion
strategy is used when testing a new tree delivered via `rpm-ostree
rebase`.
This does increase the complexity when running the playbook, but also
increases flexibility.
It would probably be worthwhile to investigate how to simplify this test
by divorcing the choice of delivery (`upgrade` vs. …

Add support for testing new tree via rebase

---

Vagrantfile

We should make it convenient for people to test this
locally, similar to what openshift-ansible has.
This is just a stub file to run the new-image-smoketest - it currently
fails, looks like because we're missing a template file.

Add a Vagrantfile to run the new-image smoketest

---

Vagrantfile
roles/rpm_ostree_upgrade/tasks/main.yml
roles/rpmdb_verify/tasks/main.yml
tests/improved-sanity-test/main.yml

This introduces a simple test of the RPM database to the sanity suite,
among other things.  Other changes:
- the `Vagrantfile` now has Fedora 24 support
- the playbook executed by the Vagrant box can be configured by an
environment variable
- the `rpm-ostree upgrade` role has been improved to check for an
available update first

add RPM db tests

---

roles/etc_modify/tasks/main.yml
roles/etc_verify_changes/tasks/main.yml

The `etc_modify` and `etc_verify_changes` roles were using the
`ansible_default_ipv4` variable to make modifications (and
verifications) to `/etc/hosts`.
This variable is actually a dictionary, so a huge string was being
inserted into `/etc/hosts` instead of a more sensical IP address.
This changes the two roles to use the correct IP address rather than
an embarrasingly long Python `dict`.

roles: fix /etc roles to just insert IP address

---

roles/etc_modify/tasks/main.yml
roles/etc_verify_changes/tasks/main.yml

While using the `improved_sanity_test` playboook in our OpenStack
environment (when driven by Jenkins), we were seeing failures when trying to
verify changes made to `/etc/hosts`.  (We did not see the same
failures when running the playbook by hand.)
The root cause was the value of `ansible_fqdn` was changing after the
host was rebooted.  I don't fully understand why this was changing
after a reboot, but in order to work around this, we can just use
`ansible_hostname` in its stead.

roles: use ansible_hostname instead of ansible_fqdn

---

roles/docker_build_httpd/files/centos_httpd_Dockerfile
roles/docker_build_httpd/files/fedora_httpd_Dockerfile
roles/docker_build_httpd/files/rhel7_httpd_Dockerfile
roles/docker_build_httpd/tasks/main.yml
roles/docker_pull_base_image/tasks/main.yml
roles/docker_remove_all/tasks/main.yml
roles/docker_rm_httpd_container/tasks/main.yml
roles/docker_rmi_httpd_image/tasks/main.yml
roles/docker_run_httpd/tasks/main.yml
roles/osname_set_fact/tasks/main.yml
tests/improved-sanity-test/info.txt
tests/improved-sanity-test/main.yml

This brings in some simple docker tests to the sanity suite.  There
are tests performed pre and post upgrade of the system.
Before the upgrade happens, a base image is pulled to be used as part
of the build process of a layered image.  The layered image is built,
run, and then the resulting container is removed.
After the upgrade, the layered image that was built is ran again, the
resulting container removed, and then the layered image is removed.
As part of this change, I also pinned the playbook to Ansible 2.1 as
it seems pretty stable and has been working well thusfar.

improved-sanity-test: Add tests for docker operations

---

roles/reboot/tasks/main.yml

During recent testing of incoming changes, some of us have noticed
inconsistency when using the `ansible_host` variable during the
'reboot' role.  Instead, the `inventory_hostname` variable has given
us more more reliability.
This somewhat flies in the face of the comment originally made in
PR #33, but live and learn.

roles: remove ansible_host reboot case

---

roles/docker_run_httpd/tasks/main.yml

The internal CI job occasionally fails because the connectivity test
to the httpd container is unsuccessful. There does not seem to be a
good reason for this, so we'll just retry a few times.

docker_run_httpd: retry connection to httpd container

---

roles/redhat_subscription/tasks/main.yaml

The subscription manager changes the remote in the refspec in the
origin file.  If the test system is pointing to other update streams
like autobrew builds, the refspec is overwritten and causes issues
with upgrading.  To fix this, the refspec is now saved when it is not
the default value and re-written after the subscription process.
This fix is particularly important for tests that deal with building
RHEL containers and upgrading to alternate remotes.  Building RHEL
containers requires entitlements from the host.  Upgrades to alernate
remotes requires the proper refspec in the origin file.

Reset refspec in origin for alternate remotes

---

Vagrantfile
roles/selinux_verify/tasks/main.yml
tests/improved-sanity-test/info.txt
tests/improved-sanity-test/main.yml

This change introduces a role that does some basic checks of the
SELinux contexts on the `ostree`, `rpm-ostree`, and `rpm-ostreed`
binaries.  It also checks the SELinux labeling of the `rpm-ostreed`
process.

Add SELinux checks for ostree/rpm-ostree

---

Vagrantfile

When trying to deploy HEAD^ for CentOS, I encountered an error because
the version of C7AH in the current Vagrant box is equivalent to HEAD^.
I adjusted the logic around the deploy to skip out if the version of
the Vagrant box happened to be HEAD^ from the remote.
Additionally, I had to use some `sed` edits to disable GPG
verification because of ostreedev/ostree#518

Vagrantfile: adjust logic for CentOS

---

roles/atomic_installation_verify/tasks/main.yml

There is an upstream issue #674 filed in the atomic CLI project for
the pull that occurs during atomic install. The pull does not
resolve the fully qualified name for the container and throws an
error. We should be using fully qualified container names so we
know we are pulling the right image from the right registry anyhow.

Use fully qualified container name for cockpit

---

roles/atomic_installation_verify/tasks/main.yml

In projectatomic/skopeo#227, the `atomic install` command is failing
because there is no explicit tag specified.
This change makes the test use the `:latest` tag explicitly on the
cockpit images.
(We may want to revert this once the upstream issue is fixed)

atomic_installation_verify: use :latest tag

---

roles/redhat_subscription/tasks/main.yaml

The redhat subscription role will save and restore the refspec for the
currently booted commit (because it gets overwritten by subscription
manager). Added a check to verify that the deployment exists so set_fact
will no longer fail.

Add check for rpm-ostree status json deployment output

---

roles/docker_build_tag_push/tasks/main.yaml
roles/docker_private_registry/tasks/main.yaml
roles/kubernetes_setup/tasks/main.yaml

The docker module is now considered deprecated. This change moves to
using the newer docker_container (2.1.0) and docker_image (1.5)
modules.
See: http://docs.ansible.com/ansible/docker_module.html#deprecated
Part of #28

Move away from deprecated docker module

---

roles/docker_build_tag_push/tasks/main.yaml
roles/docker_private_registry/tasks/main.yaml
roles/kubernetes_setup/tasks/main.yaml

This reverts commit c9877e3b8f8ae902a0830fbcb4e5239dc6fb9752.
The tests are pinned to Ansible version 2.1 so the changes to
the new docker module do not work.

Revert "Move away from deprecated docker module (#56)"

---

roles/docker_build_httpd/tasks/main.yml
roles/docker_rm_httpd_container/tasks/main.yml
roles/docker_rmi_httpd_image/tasks/main.yml
roles/docker_run_httpd/tasks/main.yml
roles/osname_set_fact/tasks/main.yml
tests/improved-sanity-test/main.yml

While debugging a recent failure on the internal autobrew stream, it
wasn't immediately obvious from the Ansible output that the httpd
container was not running.  I added a check after starting the
container to see if the container was in the output of `docker ps`.
Additionally, I opted to make use of a global variable in the httpd
image/container roles.  We previously took the `g_osname` variable and
concatenated some text onto it to make the values used in various
`docker` operations.

roles: check for presence of running httpd container

---

tests/improved-sanity-test/main.yml

This adds tags on the higher order plays contained in the
`improved-sanity-test` playbook.  This allows us even more flexibility
in running specific tests when necessary.

tests: tag individual plays in sanity test

---

roles/kubernetes_setup/files/apiserver-pod.json
roles/kubernetes_setup/tasks/main.yaml

Atomic host now requires kubernetes to be run from a container because kubernetes
was removed from Atomic Host.  The apiserver-pod file was using
/etc/kubernetes/apiserver which did not work in the fully containerized
model of kubernetes.  The contents of the apiserver file was moved into the
apiserver-pod.json file and the edits on /etc/kubernetes/apiserver was
removed from the role.

Fix apiserver for fully containerized kubernetes

---

roles/selinux_verify/tasks/main.yml

We've run into situations where the `getfattr` utility is not
installed on the host and the failure message from this role is not
explicit in that case.  So I added a check for the utility ahead of
trying to use it.
I'm not going to bother trying to check SELinux information using
different methods, since this utility should be commonly installed on
AH and if it isn't, that is a problem to flag.

selinux_verify: add check for getfattr

---

roles/var_add_files/tasks/main.yml
roles/var_files_present/tasks/main.yml

Turns out the SELinux policy on F25 has `svirt_sandbox_file_t` is an
alias to `container_file_t`
```
$ seinfo -x --type=svirt_sandbox_file_t
TypeName container_file_t
Aliases
svirt_sandbox_file_t
svirt_lxc_file_t
```
This was causing some of the SELinux checks to fail on F25, so now they are
conditional on F25.

roles: update SELinux contexts for F25

---

roles/atomic_scan_verify/tasks/main.yml

We were seeing failures on certain streams when trying to install the
`openscap` scanner from `registry.access.redhat.com`.  The version of
`skopeo` being used in these cases did not support v1 schema manifests
and that is the only version available on that registry.
Using the scanner from upstream alleviates this problem and gives us
further coverage in this space.
Oddly, only RHEL-based images are supported by the `openscap` scanner,
so the behavior has been changed to scan the RHEL7 image regardless if
the scanner used is upstream or downstream.
Finally, `atomic scan` no longer requires a TTY, so we can change
how that command is invoked.

atomic_scan_verify: use upstream scanner

---

roles/atomic_installation_verify/tasks/main.yml

With the next release (version 127) of the `cockpit-ws` container,
non-interactive (un)installs will be possible as the Dockerfile has
been updated to not use the `-ti` flags.
This change brings support for non-interactive (un)installs by
checking the version of the `cockpit-ws` RPM and proceeding accordingly.

atomic_verify_install: move to non-interactive (un)installs

---

common/atomic.yaml
roles/semanage_add_verify/tasks/main.yml

The previous change to test semanage for /var/lib/kubelet fails if the host
doesn't have kubelet installed, as is the case for CAHC.
Add a global `have_builtin_kube` fact that we can use elsewhere too.

Fix handling of systems (CAHC) with no builtin kube

---

roles/docker_build_httpd/files/centos_httpd_Dockerfile
roles/docker_build_httpd/files/fedora_httpd_Dockerfile
roles/docker_build_httpd/files/makecache.sh
roles/docker_build_httpd/files/rhel7_httpd_Dockerfile

We have seen failures in the tests that appear to be related to
network issues (either in our OpenStack infra or in the Fedora infra)
when trying to install `httpd` while building the Docker image.
To combat this, we just steal the [env_make_cache()](https://github.com/jlebon/redhat-ci/blob/master/testrunner#L267)
routine from @jlebon and stick it in a dumb script.  Then we `ADD` to
the Docker image and `RUN` it before trying to install any packages.
This does add some extra instructions and time while building the
Docker image, but should help us avoid these network related failures.

docker_build_httpd:  add makecache.sh script

---

roles/docker_build_httpd/tasks/main.yml

While the inclusion of the `makecache.sh` script is nice, it would
help if we actually copied it over to the host under test.
I used a separate `copy` statement to give the script executable
permissions, which the Dockerfile does not require.

docker_build_httpd: copy makecache.sh script

---

roles/user_add/tasks/main.yml
roles/user_verify_present/tasks/main.yml

CentOS, Fedora, and RHEL Atomic Host all conveniently use SHA-512 to
hash their passwords.
These changes verify that the hashing algorithm is correctly
configured to SHA-512 and also verifies that hashed passwords are
correctly stored in `/etc/shadow`
The password is randomly generated via `uuidgen`, then fed into
`passwd`.  The hash is confirmed by searching for the user and the
leading `$6` on the password hash in `/etc/shadow`.
See `man crypt` for details about the hashing algorithms.

users: verify password hashing algorithm

---

roles/selinux_verify/tasks/main.yml

This way we're robust against any process renames.

selinux_verify: Use systemd to find MainPID for rpm-ostreed

---

roles/docker_pull_run_remove/tasks/main.yml
roles/docker_pull_run_remove/vars/main.yml
tests/improved-sanity-test/main.yml

This is a really simple role that just checks we can pull, run, and
remove some of the more popular images on the Docker Hub.
Useful?  Meh.  Kind of just a checkbox because my $dayjob boss asked
me to include it.  :)

roles: add role to pull/run/remove "popular" images

---

.redhat-ci.yml
common/ans_ah_head-1_deploy.yml
common/ans_reboot.yaml

Now that we have a known working tree with the CAHC smoketested branch,
we can spin this around and use it to automatically test new additions
to the improved sanity tests.
Of course, if we're adding new tests that catch bugs that are already
present in the latest smoketested branch, the PR tester will fail. Thus,
this is not meant to be used with a merge bot, but rather a general
indication of how sane a PR is.

repo: add .redhat-ci.yml

---

common/ans_reboot.yaml
roles/reboot/tasks/main.yml
tests/improved-sanity-test/main.yml

Occasionally, we have seen instances where the `docker` daemon was not
starting quickly enough after a reboot, causing subsequent tasks to
fail.  This change attempts to mitigate that by introducing the ability to specify a list of
services to check when rebooting the host.
It's slightly messy because we have a `reboot` role and the
`ans_reboot.yaml` file that can be included.  So I went the
conservative route and made sure there were defaults specified for
both cases.
I've only changed the use of the `reboot` role in the
`improved-sanity-tests`.  Other places in that suite or in other tests
that reboot the host have not been changed.

reboot: provide ability to check for started services after reboot

---

README.md
Vagrantfile
tests/admin-unlock/README.md
tests/docker-swarm/README.md
tests/docker/README.md
tests/improved-sanity-test/README.md
tests/pkg-layering/README.md
tests/system-containers/README.md

I happened to notice that the READMEs that we include for each of the
test suites mention running `vagrant up` to execute the playbook.
This wasn't entirely correct, since the individual tests suites don't
have a Vagrantfile in their directory.
So I removed that section from the READMEs and cleaned up the top
README to explain how to run different playbooks using the included
Vagrantfile.
Additionally, I tried to clean up the top-level README to be more
useful and correct.

docs: tidy up information regarding Vagrant

---

roles/atomic_host_status_verify/tasks/main.yml
roles/redhat_unsubscribe/tasks/main.yml
tests/improved-sanity-test/main.yml

Our internal testing found that trying to use `rpm-ostree status` on a
RHELAH host that was not registered via `subscription-manager` would
fail. See [RHBZ
1421867](https://bugzilla.redhat.com/show_bug.cgi?id=1421867)
To test for this, I've re-arranged when we use `rpm-ostree status` and
added a role that removes any subscriptions from a host and drops an
`unconfigured-state` field into the origin file (optionally).

add a test for rhbz 1421867

---

callback_plugins/default.py
tests/admin-unlock/callback_plugins
tests/docker-swarm/callback_plugins
tests/docker/callback_plugins
tests/improved-sanity-test/callback_plugins
tests/k8-cluster/callback_plugins
tests/multiple-rollback-reboot/callback_plugins
tests/multiple-rollback/callback_plugins
tests/new-image-smoketest/callback_plugins
tests/new-tree-smoketest/callback_plugins
tests/pkg-layering/callback_plugins
tests/rollback-interrupt/callback_plugins
tests/system-containers/callback_plugins
tests/unique-machine-id/callback_plugins
tests/upgrade-interrupt/callback_plugins

Added a callback_plugin that makes the logs more human readable and
also saves down failure details to a file.
A majority of this code is actually from other projects.  The code
that alters the Ansible output is from openshift-ansible which is
derived from an upstream project (in the comments).  I had to override
the baseclass methods to track the failure details.  In order to
preserve the default Ansible logging, I copied the original method
code back into the override method.
All test that want to leverage the callback_plugin need a symlink to
the top callback_plugins directory otherwise the default Ansible logging
will be used.

Save failure details to result file

---

roles/atomic_scan_verify/tasks/main.yml

As of about 3:30pm today, there is no more
`docker.io/fedora/atomic_scan_openscap` image.  This image was part of
the old 'Fedora Dockerfiles' repo, which is being migrated to the new
Fedora Registry and OSBS.
As such, we need to revert to using the scanner from the Red Hat
registry and make a small modification to the scanner config file as a
result.

atomic_scan_verify: remove upstream scan image

---

callback_plugins/default.py

The code was capturing all failures including ones that are purposely
ignored in the playbook. I changed it so it would respect ignore
errors and only save the actual failure.

Utilize ignore errors when saving failure

---

callback_plugins/default.py

ignore_errors is set to None when it is passed into v2_runner_on_failed
which will not capture any failures except when the calling function
does not pass an ignore_errors parameter.  I swapped it to capture the
failure in all cases except when ignore_errors is explicitly set to
true.

Handle None case for ignore_errors

---

roles/selinux_boolean/tasks/main.yml
roles/selinux_boolean_verify/tasks/main.yml
roles/selinux_verify/tasks/main.yml
roles/selinux_verify/vars/main.yml
tests/improved-sanity-test/main.yml
tests/improved-sanity-test/vars.yml

This commit expands the scope of our SELinux checks to include the
validation of the SELinux labels on multiple key processes and files.
It also checks that any files on the filesystem do not have the
default labels `default_t` or `file_t`.
Finally, it includes a simple test to validate that changes made
to an SELinux boolean will persist through the upgrade/reboot cycle.
This particular test covers [RHBZ#1381588](https://bugzilla.redhat.com/show_bug.cgi?id=1381588)

expand SELinux tests

---

tests/improved-sanity-test/main.yml

The main outcome of this change is to introduce a tag that allows
users to run the `improved-sanity-test` playbook against a freshly
minted cloud image.  This causes portions of the playbook to be
skipped, most notably the upgraded and rollback tests.  The idea for
this addition came from the observation that Fedora runs tests via
`autocloud` against each new Atomic Host cloud image that produced
every night.
To use this new tag, a user would invoke the playbook with the `--tag
cloud_image` value:
`$ ansible-playbook -i inventory tests/improved-sanity-test/main.yml --tag cloud_image`
Currently, the order of tests/operations for this new tag should look
like this:
- compare `atomic host status` vs `rpm-ostree status`
- verify SELinux labels
- modify SELinux file contexts
- check `docker …

i-s-t: add tag for testing cloud image

---

tests/pkg-layering/main.yml

Package layering support was added for non-root packages.  There was
a negative test to make sure non-root packages could not be installed
that is now replaced with a test to make sure non root packages can
be installed.

Add test for non-root package layering

---

.redhat-ci.yml

We know that the SELinux tests are going to fail because of the
following [RHBZ#1381588](https://bugzilla.redhat.com/show_bug.cgi?id=1381588)
So we will skip them for now.

Skip the SELinux tests temporarily

---

.redhat-ci.yml
roles/selinux_verify/tasks/main.yml
roles/selinux_verify/vars/main.yml

Rather than configure all the executors of the tests to skip an entire
role, we'll just comment out the failing part of the role until the
necessary bug ([RHBZ #1381588](https://bugzilla.redhat.com/show_bug.cgi?id=1381588)) is fixed.

Re-enable SELinux tests

---

roles/httpd_start/tasks/main.yml
roles/rpm_ostree_install_verify/tasks/main.yml
roles/url_verify/tasks/main.yml
tests/improved-sanity-test/main.yml
tests/improved-sanity-test/vars.yml

A new feature was added to allow non-root packages to be layered
using rpm-ostree install.  Instead of using a simple package like
wget, the httpd package  tests a broader code path because it has
multiple dependencies, creates an apache user, and is a non root
package.
The default settings for httpd conflicted with the docker container
tests in improved sanity tests so it was changed to port 8080 in the
httpd_start role.  The httpd service is validated by retrieving the
default apache page.

Change to more complex rpm-ostree install package

---

roles/atomic_host_check/tasks/main.yml
roles/httpd_start/tasks/main.yml
tests/improved-sanity-test/main.yml

When running playbooks that use the `always_run` option¸ Ansible 2.2
will print a deprecation warning that states that users should switch
to `check_mode: no` instead.
Additionally, another warning is printed about using `port` as a
parameter to role.  The offending role was `httpd_start` and it was
updated to use a different parameter name.

Small fixes for Ansible 2.2 support

---

tests/improved-sanity-test/main.yml

We have been seeing multiple failures during the `atomic scan` tests
because of an incompatibility between overlay mounts and SELinux.
This won't be fully fixed until RHEL 7.4 ships, so we'll just work
around it for now.

Move 'atomic scan' tests ahead of 'ostree admin unlock'

---

roles/docker_build_httpd/files/rhel7_httpd_Dockerfile
roles/docker_build_httpd/files/rhel_makecache.sh
roles/docker_build_httpd/tasks/main.yml

We have seen instances on RHEL hosts where the `makecache.sh` script
inside the `docker build` process tries to generate the cache for every
repo a subscription provides.  Not only is this costly in terms of
time required to generate the cache, but it is also incorrect since we
explicitly disable all the repos and re-enable only those we care about
during the subscription phase.
To work around this, a copy of the `makecache.sh` script was made with
RHEL specific instructions to use only certain repos.

Fix metadata cache generation for RHEL case

---

README.md

This commit adds a status table of the latest improved sanity test
runs for the streams we test.  It uses shields.io badges containing
the version and result of the test run.  The badges are not directly
from shields.io, instead badges and logs are saved in a s3 bucket.

Add status table to repo landing page

---

callback_plugins/default.py

Captures the unreachable message in the result array when there is
a connection error while running a playbook.

Handle unreachable scenario in callback plugin

---

tests/improved-sanity-test/main.yml

I was debugging what turned out to be a user error and saw that we
actually called the `reboot` role twice in the `pre_upgrade` stage.
While I was in there, I thought it would make sense to diverge from
the typical tag naming guidelines and give each `reboot` role a unique
tag.

Cleanup some of the reboot usage

---

tests/improved-sanity-test/main.yml

Adds a check for running rpm-ostree status as a non-root user pre
and post upgrade.

Verify rpm-ostree status as non-root

---

roles/rpm_ostree_uninstall_verify/tasks/main.yml
tests/pkg-layering/main.yml

The functionality for package layering has changed slightly so the
test need to be updated.  Two tests were added to verify the new
fucntionality.  The first test verifies that packages that are
being layered is added to a list of requested packages even if it is
already in the deployment.  The second test is that rpm-ostree should
error out when attempting to layer a package that already exists.
There was also a change in the rpm-ostree status output.  When there
are no packages are layered, there will be no "packages" listed in
the rpm-ostree status output. This caused an error when setting facts
in  rpm_ostree_uninstall_verify role.  To get around this, I only
set the fact to {} if it is undefined or to the list of packages if
it is defined.

Add additional tests for package layering

---

roles/redhat_subscription/tasks/main.yml
roles/redhat_unsubscribe/tasks/main.yml

This changes how we manipulate the origin files by using `ostree admin
--print-current-dir` to derive the origin file.  This gains us more flexibility because the origin file does not always live at `<commit>.0.origin`.

redhat_subscription: rework handing of origin files

---

tests/system-containers/main.yml

Update the test to reflect the symlink of the rootfs dir when using
--rootfs.  See https://github.com/projectatomic/atomic/pull/922

Check for rootfs dir in remote sys container

---

tests/system-containers/main.yml

We should start using system containers from the Fedora registry for
non-RHEL systems.

Start using images from the Fedora registry

---

roles/atomic_images_delete_all/tasks/main.yml
roles/k8_remove_all/tasks/main.yml
roles/rpm_ostree_cleanup_all/tasks/main.yml
tests/admin-unlock/main.yml
tests/docker-build-httpd/README.md
tests/docker-build-httpd/main.yml
tests/docker-swarm/main.yml
tests/docker/main.yml
tests/k8-cluster/main.yml
tests/pkg-layering/main.yml
tests/runc/main.yml
tests/system-containers/main.yml

If we want to run the tests in succession, we should cleanup what the
tests have left around.  This typically includes docker
images/containers, kubernetes artifacts, and layered packages.
This change attempts to cleanup after most* tests and return the host
under test to its original state.  This includes two new roles that
assist in the cleanup of the host.
* The improved-sanity-test and system-containers test were not
addressed in this change, but should be addressed in the future.

Cleanup after test completion

---

roles/selinux_verify/vars/fedora-24.yml

I got tired of seeing the Fedora 24 test failing on SELinux checks, so
I created the necessary config for it.

roles: fix selinux_verify for F24

---

callback_plugins/default.py
roles/handler_notify_on_failure/handlers/main.yml
roles/handler_notify_on_failure/tasks/main.yml
tests/improved-sanity-test/main.yml

This commit will collect the journal for the improved sanity test and
save it locally.  It also enables running other tasks on failure.
This is a giant workaround since Ansible does not have direct support to
run post execution tasks on failure..  Ansible's only mechanism for running
tasks after a play completes is a handler.  The problem with a handler
is that it will not run on failure without the force_handlers set to true.
If force_handlers is set to true it will run after every block of
pre_tasks, post_task, roles, and plays (not desirable).  The way to
workaround that is to conditionalize the tasks to only run when there
is a failure; however, Ansible does not have a direct variable that holds
the pass/fail status of a playbook.
In order to get the fail status, I leveraged the …

Collect journal on failure

---

roles/atomic_installation_verify/tasks/main.yml

While testing an `atomic` update manually, I hit an issue
(projectatomic/atomic#995) that I thought our tests should have
caught.  And when I examined this role as a response, I realized there
were some improvements to be made.
- Switch to using the cockpit image from the Fedora registry
- Stop checking the cockpit version (turns out the version check never
worked)
- Run the same commands twice; one specifying the `:latest` tag and
once without a tag
- Stop the container before uninstalling

roles: rework atomic_installation_verify

---

roles/atomic_run_verify/tasks/main.yml

In a recent FAHC test run [0], it failed with the following error:
```
The conditional check '(dps.stdout.find("Up") == -1 and
dps.std.outfind("Created") == -1)' failed. The error was: error while
evaluating conditional ((dps.stdout.find("Up") == -1 and
dps.std.outfind("Created") == -1)): 'dict object' has no attribute
'std'
The error appears to have been in
'/home/jenkins/workspace/atomic-host-jobs-treecompose-improved-sanity-test-fahc/atomic-host-tests/roles/atomic_run_verify/tasks/main.yml':
line 22, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
```
Turns out there was a small typo in that role, which is fixed in this
change.
[0]
https://s3.amazonaws.com/aos-ci/atomic-host-tests/improved-sanity-test/fahc/jenkins-atomic-host-jobs-treecompose-improved-s …

Fix typo in atomic_run_verify

---

roles/redhat_subscription/tasks/main.yml

It's almost always a good idea to protect in-flight credentials.  Wrap
the username & password values inside temporary environment variables.
These env. vars. only exist for the life of the ``bash`` process.
Though they will still be exposed in a process-listing (on the target),
they won't show up inside any ansible logs.
Signed-off-by: Chris Evich <cevich@redhat.com>

Hide subscription-manager username/password

---

roles/redhat_subscription/files/subscription_data.csv.sample
roles/redhat_subscription/tasks/main.yml

Sometimes additonal options are needed during registration, such as
``--force`` or ``--org``.  Support this with an optional 'extra' key in
the CSV file.  When this key is not present, treat it as an empty
string to the sub. man. command-line.
Signed-off-by: Chris Evich <cevich@redhat.com>

Support passing extra options to sub. man.

---

roles/redhat_subscription/tasks/main.yml

In #153  support was added for passing extra arguments to the
subscription manager command.  If no value was defined in the
subscription csv for 'extras' the lookup command would return []
which would then be added to the end of the subscription manager
command and fail.  Since the return from the lookup is [], the
jinja2 default filter of empty string did not get applied.
The fix I came up with was to set extra_args to the extras lookup
only if the extra lookup is not [].  Otherwise it will set it to
empty string.  This preserves backwards compatability to the old
subscription csv format for people that are already using the test.

Use empty string for extra args if undefined

---

requirements.txt

In the previous version, `requirements.txt` would install Ansible 2.3.  Probably wouldn't break anything, but let's just stay paranoid and require users to stick at 2.2

Adjust requirements.txt to stay at 2.2.x

---

CONTRIBUTING.md
docs/howto_contribute.md

It was requested that additional documentation be made available about
how to start contributing to the repo.  I've created a new `docs`
directory that currently holds a single file that goes into some of
the details of the repo and how to create roles/tests.

docs: howto contribute to the repo

---

.test_director

#173 did not handle the scenario where improved-sanity-test is the modified test.  
This PR will run the HEAD-1 deployment script if it finds the improved-sanity-test
in the list of files in the git diff output.  Keep this logic until #150 is resolved.

Handle improved-sanity-test scenario in PAPR

---

.test_director

The inventory file was accidentally pointing to a test machine instead
of the testnode.

Fix inventory for running improved sanity test

---

.test_director

The two dot notation used originally does not work the same way in
git diff as other git commands.  Git diff expects two endpoints as
opposed to a range.  This was causing the diff to return files that
were not a part of the PR to be included in the automatic tests that
are run when there is a new PR.

Use correct git diff to determine tests to run

---

tests/docker-build-httpd/main.yml
tests/docker-build-httpd/tasks/build_run_remove.yml

I ran into the following bug while testing:
https://bugzilla.redhat.com/show_bug.cgi?id=1460341
...and realized there was no easy way to skip the images that were
failing.  This was frustrating, so I fixed it.
The test can now accept an extra var named `cli_skipped_images` which
will take a string of image names to be skipped by the test.  If the
name of the current image under test is in that string, the test skips
that image.
There is no validation that the string contains valid values or
anything like that, so it is up to the user to be smart when using it.

tests: allow users to skip images in docker-build-httpd

---

roles/selinux_verify/vars/fedora-27.yml

The `selinux_verify` role was failing when run against the Rawhide
version of Atomic Host.  Rawhide Atomic Host reports itself as Fedora
27 via Ansible, but has the same files/procs as Fedora 26 (in the
context of this role), so just symlink to the `fedora-26.yml`.
Closes #180

selinux_verify:  enable support for rawhide

---

roles/atomic_scan_verify/tasks/main.yml

We no longer need to modify `/etc/atomic.d/openscap` because the
OpenSCAP container we use has been fixed.
See [RHBZ#1418464](https://bugzilla.redhat.com/show_bug.cgi?id=1418464)

atomic_scan_verify:  remove /etc/atomic.d/ workaround

---

roles/selinux_verify/tasks/main.yml
roles/selinux_verify/vars/redhat-7.4.yml

In RHELAH 7.4, a few changes made that required an update to the files
being checked for SELinux labels.
This allows to test RHELAH 7.3 and the pre-release version of RHELAH
7.4 at the same time.  When 7.4 is released, we could remove this
specialized file if we decide to.

selinux_verify: add support for RHELAH 7.4

---

tests/improved-sanity-test/main.yml

When running the `improved-sanity-test` using `--tags cloud_image` the
system is left with a 'hotfix' deployment in the waiting.  If we want
to use the system again to run additional tests, the nice thing to do
is to cleanup after ourselves.
In the case of normal execution, where the system starts at HEAD-1,
upgrades, than rolls back to HEAD-1, we will end up cleaning the
deployment at HEAD.  I'm of the opinion this isn't a deal-breaker.

i-s-t: cleanup any extra deployments at the end

---

roles/atomic_pull_verify/tasks/main.yml

We no longer need to check the version of the `atomic` command in
order to determine how to list images with the command, since all the
platforms we test against are at version 1.12+ of `atomic`.
Additionally, I added a retry loop on the `atomic pull` in order to
mitigate any failures due to network problems.
This address a small sliver of #156

roles: implement retries and remove version check

---

roles/atomic_installation_verify/tasks/main.yml
roles/atomic_scan_verify/tasks/main.yml
roles/atomic_system_install/tasks/main.yml
roles/docker_pull_base_image/tasks/main.yml
roles/docker_pull_run_remove/tasks/main.yml
roles/epel_rpm_url/tasks/main.yml
roles/rpm_install/tasks/main.yml
roles/rpm_ostree_install/tasks/main.yml
roles/rpm_ostree_rebase/tasks/main.yml
roles/rpm_ostree_upgrade/tasks/main.yml

This adds retry logic to roles that rely on external network
operations.  I settled on 5 retries per action with delays of 60s
between each attempt.  This should help mitigate some of the failures
we encounter when the network is flaky.
Additionally, I re-wrote some of the existing retries to follow the
format of:
```
register: <var>
retries: 5
delay: 60
until: <var>|success
```
This makes our retry logic more consistent across roles.
This is another commit to address #156

roles: add retries to network operations

---

tests/system-containers/main.yml

We should be removing our subscriptions at the end of the
`system-containers` test.

tests: unsubscribe at end of system-containers test

---

tests/docker-build-httpd/main.yml
tests/pkg-layering/main.yml
tests/rpm-ostree/main.yml
tests/system-containers/main.yml

Some of the tests use bare tasks to perform the operations they need,
so I've implemented retries on those that access the network.
Any existing retries that I found were rewritten to the new format of:
```
register: result
retries: 5
delay: 60
until: result|success
```

tests: implement retries on network operations

---

roles/rpm_ostree_uninstall/tasks/main.yml
tests/improved-sanity-test/main.yml

Sometimes you just want all the installed packages removed, so this
introduces support for the `all` keyword in the `rpm_ostree_uninstall`
role.  It is not 100% bulletproof, since it is possible a user could
use the `all` keyword when there is nothing installed and then the
role will probably blow up.  But I'm hoping that we are better than that.
There could be additional work done in the
`rpm_ostree_uninstall_verify` role to support the `all` keyword, too.
But I was unable to arrive a solution that would both verify the
packages were uninstalled and the binaries were removed.

add support for removing all installed packages

---

.papr.yml

Today is the release of Fedora 26, so we should start using it in our
own PAPR tests.

Enable Fedora 26 testing via PAPR

---

roles/command/tasks/main.yml
roles/etcd_sys_container_install/tasks/main.yml
roles/shell/tasks/main.yml
tests/improved-sanity-test/main.yml

etcd_sys_container_install role:
This check-in is a simple system container test for the improved sanity test (IST)
Because the IST is comprised of only roles (and cannot be mixed with tasks), the
etcd_sys_container_install role was made specifically to validate the install
and configuration of etcd for IST.
improved sanity test:
In the IST, the etcd system container is installed and configured pre-upgrade
and checked post upgrade for its existence.  Then it is removed and re-installed
to test the system container installation on HEAD.  On a cloud_image test, the
installation, configuration, and uninstallation is only checked once in the post
upgrade section. This was done to ensure we have some coverage on the upgrade
scenario and when running the test on a cloud_image with no upgrade. …

Add etcd system container test to I-S-T

---

roles/docker_build_httpd/tasks/main.yml
roles/docker_latest_setup/tasks/main.yml
tests/docker/main.yml

The more recent versions (1.13, I think) of `docker-latest`
require additional lines to be modified in `/etc/sysconfig/docker` for
everything to play happy together.
Closes #192

Update handling of /etc/sysconfig/docker for docker-latest

---

roles/docker_build_httpd/files/centos_httpd_Dockerfile
roles/docker_build_httpd/files/fedora_httpd_Dockerfile
roles/docker_build_httpd/files/rhel7_httpd_Dockerfile
roles/docker_build_tag_push/files/centos/db/Dockerfile
roles/docker_build_tag_push/files/centos/web/Dockerfile
roles/docker_build_tag_push/files/fedora/db/Dockerfile
roles/docker_build_tag_push/files/fedora/web/Dockerfile
roles/docker_build_tag_push/files/rhel7/db/Dockerfile
roles/docker_build_tag_push/files/rhel7/web/Dockerfile
tests/docker-build-httpd/files/alpine_httpd/Dockerfile
tests/docker-build-httpd/files/apache_httpd/Dockerfile
tests/docker-build-httpd/files/busybox_httpd/Dockerfile
tests/docker-build-httpd/files/debian_httpd/Dockerfile
tests/docker-build-httpd/files/nginx_httpd/Dockerfile
tests/docker-build-httpd/files/rhel7-atomic_httpd/Dockerfile
tests/docker-build-httpd/files/rhel7_httpd/Dockerfile
tests/docker-build-httpd/files/ubuntu_httpd/Dockerfile

The Dockerfiles we use in our tests had a myriad of FROM formats, so
this cleans up the state of those.  Now all the FROM lines have the
following:
- fully-qualified domain
- explict tag (:latest or otherwise)
Additionally, the CentOS and Fedora base images are changed to be
pulled from the community registries instead of docker.io

Update Dockerfiles to use proper FROM field

---

.papr.yml

The `centos/7/atomic` and `centos/7/atomic/smoketested` distros are
having issues that are affecting our PAPR tests.  I've removed them
temporarily until they are stable again.
Related issues:
CentOS/sig-atomic-buildscripts#282
CentOS/sig-atomic-buildscripts#283

Remove broken distros from papr.yml

---

roles/docker_private_registry/tasks/main.yml

Supported is needed for an additional  scenario now for adding
registries and insecure registries.  The current way to add
registries is in /etc/sysconfig/docker.  The new way is to add
registries to /etc/containers/registries.conf which uses yaml
format.  If /etc/containers/registries.conf exists, it the
registry will be added in the file, otherwise it will be added
in /etc/sysconfig/docker.

add support for /etc/containers/registries.conf

---

tests/improved-sanity-test/main.yml

This checks that the default Docker storage configuration is
correct/expected as part of the sanity test.

i-s-t: add check for default Docker storage config

---

roles/redhat_subscription/tasks/main.yml

When provisioning RHELAH hosts in our interal Jenkins jobs, we end up
with an origin file that has an `unconfigured-state` present.  And
when the system is registered via `subscription-manager`, that line is
not removed as part of the process.
This changes the `redhat_subscription` role to remove the
`unconfigured-state` line in the current origin file.  If the line is
already missing, this is no-op.

redhat_subscription: remove unconfigured-state after registering

---

.test_director

We shouldn't need this anymore since we support running directly on
`HEAD`.
Closes: #215

.test_director: no longer deploy HEAD-1

---

roles/journal_fatal_msgs/meta/main.yml
roles/journal_search/tasks/main.yml
tests/improved-sanity-test/main.yml

This introduces two roles that can be used for checking the journal of
a host for particular strings.
`journal_search`:  A role that will search the journal for a specific
string supplied to the role.  Optionally can specify
that the role fails when the string is found.
`journal_fatal_msgs`:  A 'meta' role that calls out to `journal_search`
to look for certain phrases that are considered
fatal to the overall test.
The `journal_fatal_msgs` role is used in the `improved-sanity-test` to
inspect the state of the journal before and after the host is
rebooted during the test duration.
Closes #186

Add support for checking the journal for strings

---

roles/journal_fatal_msgs/meta/main.yml
roles/journal_search/tasks/main.yml
tests/improved-sanity-test/main.yml

This updates the SELinux denial string that is sought to be more precise
to denials related to SELinux.
Additionally, I added more tags to the `journal_fatal_msgs` roles used
in the `improved-sanity-test` to allow better selection of which roles
should or should not run.

Minor improvements to checking the journal for fatal messages

---

roles/booted_deployment_set_fact/tasks/main.yml

If the `booted_deployment_set_fact` role is used after the host has
been upgraded/rebased to a local branch, it will currently fail
because the refspec has no `remote` portion.
This fixes the role to work with a local branch by checking for the
`remote:refspec` syntax (just the presence of the `:` actually) and
then setting up the facts appropriately.

roles:  fix b_d_s_f to work with local branches

---

callback_plugins/default.py

Resolves issue #217 
Ansible has a no_log option that will hide stdout and stderr when
set to true.  The callback plugin was not respecting this option
when formatting the ansible output.  This commit checks the result
_ansible_no_log value before adding it to the output.

hide stdout and stderr when no_log is true

---

.papr.yml

We were having issues deploying `HEAD-1` of the CentOS AH stream,
because the commit history of that stream had an unsigned commit in
it.  Since we no longer need to deploiy `HEAD-1` for the purposes of
running the `improved-sanity-test`, we can add the broken stream back
in.
Note:  I believe the `centos-atomic-host/7/x86_64/devel/smoketested`
branch still has issues, so I am leaving this out for now.

.papr.yml: Add CentOS AH back to PAPR coverage

---

roles/rpm_ostree_rebase/tasks/main.yml

The `rpm-ostree rebase` command supports multiple variations and this
change aims to support them with the `rpm_ostree_rebase` role.
Basic variations that are suported:
- remote:branch
- remote:branch commit
- :local-branch
- :local-branch commit
The role employs a bit of input checking to make sure there is
something usable, but it is still possible for a careless user to
provide inputs that will make it blow up.

roles: refactor rpm_ostree_rebase to support more variations

---

callback_plugins/default.py

The `_ansible_no_log` variable does not appear to be defined by
default by Ansible.  This was causing the callback plugin to suppress
any error messages about other undefined variables in a task, as
described in #226.
This change causes the variable to be initialized to `False` if the
variable is found to be undefined.  Doing so allows the other
undefined errors to bubble up.
Closes #226

callback_plugins: init '_ansible_no_log' in plugin

---

.papr.yml
requirements.txt

If we want to use the `json_query` filter in our roles (and we do), we
need the `jmespath` library installed.

papr: install 'python2-jmespath'

---

roles/rpm_signature_verify/tasks/main.yml

It turns out that you can't conditionally set a fact in Ansible and
provide a default at the same time.  So we initialize the fact first
to a default variable and then apply the conditial to set it.`

roles: init the 'rsv_rpm_sig_supported' fact

---

roles/atomic_installation_verify/tasks/main.yml

There is a new requirement that does not allow uninstall if a
container is using the image.  See [1] for details.  This includes
exited containers.  This was causing a failure in this test so
now the exited container is deleted before uninstallation.
[1] https://github.com/projectatomic/atomic/pull/1050

Delete container before uninstall

---

tests/improved-sanity-test/main.yml

At the beginning of the `improved-sanity-test`, we run the
`rpm_signature_verify` check to ensure that the supported streams are
checked to have the correct RPM signatures.  We skip this check on
certain streams which are known not to always have RPMs signed by a
single key.
Because the upgrade is performed against a local branch created from
the original commit, the content of the local branch is already well
known and has been checked for RPM signatures.  Thus we can skip the
RPM signature check for the second time.

tests: drop 'rpm_signature_verify' after upgrade

---

roles/selinux_verify/vars/fedora-28.yml
roles/selinux_verify/vars/fedora.yml

Now that fedora 27 has branched from rawhide we need to add
a fedora 28 profile. Also let's update the generic fedora symlink
to point to fedora-28.

Update fedora vars files now that 27 has branched.

---

.papr.yml

In #220, I tried to get fancy with some Ansible conditionals and
default filters, but failed to test all the possible paths, resulting
in false failures.  One of the missing paths was testing with CAHC, so
I think it would be useful to include that in the automated PAPR
checks.

papr:  add CAHC to the list of hosts

---

roles/selinux_verify/tasks/main.yml

This should help readers understand whether the test should be adjusted
or the label truly is wrong.

selinux_verify: also print expected values

---

roles/selinux_verify/vars/centosdev-7.yml

The CAHC stream started picking up RPMs from the CentOS 7.4 release,
which resulted in a few changes to the list of files and processes we
want to check.

selinux_verify:  update files/procs for latest 7.4 content

---

roles/selinux_verify/vars/centos-7.yml

CentOS AH was recently updated to match the RHEL release, so we have
to adjust our SELinux checks.

roles: update SELinux checks on CentOS AH

---

roles/kubernetes_setup/tasks/main.yml

The previous approach to adding required options to the `KUBELET_ARGS`
did not take into account that there could be default options passed
in as args.  This changes uses the `lineinfile` module and its regexp
capabilities to match the `KUBELET_ARGS` line in the file and append
the options we want to the existing line.
Additionally, the `--config` flag for the kubelet was marked as
'Deprecated' way back in Aug 2016[0] and then completely removed in Jan
2017[1].  The replacement option is `--pod-manifest-path`.
[0] https://github.com/kubernetes/kubernetes/commit/e43ccdbf2c0b69bfa19108a4d82894962c108016
[1] https://github.com/kubernetes/kubernetes/commit/bec6635ccc05b1f02c9971ec9bf529faac0b9ca1

roles:  use new regexp method to append kube options

---

roles/redhat_subscription/files/subscription_data.csv.sample
roles/redhat_subscription/tasks/main.yml

subscription_data.csv.sample got an extra parameter.
We can use this extra parameter to subscribe with activationkey for example.
extra,--activationkey='...' --org='...'
If we do so, roles/redhat_subscription/tasks/main.yml:46 raise an error:
"Error: Activation keys cannot be used with --auto-attach."
Move --auto-attach in subscription file sample.
Remove --force because extra param is already set
This PR fixes #249

Move subscription-manager auto-attach parameter in subscription file

---

tests/rpm-ostree/main.yml

I had hoped that the latest two week release of F26 (26.141) would
have picked up the version of `rpm-ostree` (2017.9) which included a
fix for projectatomic/rpm-ostree#976, but that version was stuck in
Bodhi purgatory waiting for karma and missed the compose.  :rage:
Because that issue is impacting some of our PR testing, this change
temporarily switches to restarting the `rpm-ostreed` service for the
F26 case.  Once the *next* two-week compose is released, we will
should revert this change.

tests/rpm-ostree: don't try to 'rpm-ostree reload' on F26

---

roles/reboot/meta/main.yml
roles/rpm_ostree_status/meta/main.yml
roles/rpm_ostree_status/tasks/main.yml
roles/rpm_ostree_status_verify/meta/main.yml
roles/rpm_ostree_status_verify/tasks/main.yml
roles/rpm_ostree_status_verify/tasks/rpm_ostree_status.yml
tests/admin-unlock/main.yml
tests/rpm-ostree/main.yml

This attempts to streamline the `rpm_ostree_status` role by employing
the `json_query` filter.  We can query the `deployments` from the
output of `rpm-ostree status --json` for the correct deployment which
is booted or not booted.  In the case of a single deployment, we
default to setting the `ros_not_booted` to false.
The `rpm_ostree_status_verify` has been converted to use the
json_query filter as well.  In this role, the `rpm_ostree_status` is
symlinked into the directory, so it can be included directly.  This
was done because we want to have that role run every time the 'verify'
role is called.  (I tried to use the meta dependencies, but it would
only run once per playbook if the 'verify' role was called multiple
times)
I also snuck it a little fix to the `admin-unlock` test that I …

roles: refactor 'rpm_ostree_status*' to use json_query filter

---

roles/journal_fatal_msgs/meta/main.yml
roles/journal_search/tasks/main.yml

Previously, when the `journal_search` role would fail, it would only
print a message saying that the matching line had been found.  This is
only partially useful if you want to see the actual matching line in
the test output.
This changes the `journal_search` role to crudely print the matching
lines by way of running a `grep` against the output of `journalctl`
after a match has been found.  The reason for doing this operation
after the match has been found is because the command `journal | grep
<string>` may end up in the journal if it is run with elevated
privileges via Ansible (i.e. using `sudo`)
Closes #253

roles: print matching lines from journal

---

roles/booted_deployment_set_fact/tasks/main.yml
tests/improved-sanity-test/main.yml

If you ran a long test that used the `booted_deployment_set_fact` role
across multiple hosts in parallel, any archive file that was created
by the test would be clobbered by the last execution that completed.
This creates a problem when you are trying to read that file and
expecting it to have certain values.
To avoid this, the archive file is created with the value of
`ansible_host` prepended to the file name.  This keeps the file unique
to the host under test and should avoid any clobbering that may have
happened.
Closes #258

roles/bdsf: prepend 'ansible_host' to archive file

---

tests/system-containers/main.yml

On certain flavors of Atomic Host, we still ship the `etcd` and
`flannel` RPMs on the host.  This causes a minor conflict when we
install those services from system containers.  Notably, the existing
services can be running and attempts to `runc exec` into the
containers will fail because they haven't been started yet.
So we check for the presence of the RPMs and proactively disable/stop
the services before trying to use the system containers.

system-containers: disable etcd/flanneld if rpms are installed

---

tests/improved-sanity-test/main.yml
tests/improved-sanity-test/vars/common.yml

Previously, we were getting away with using `epel-release` as a
generic RPM duing the `rpm_install` role in the i-s-t.  But the latest
version of the RPM now has a `Conflicts: fedora-release` and thus we
can't install it on Fedora-based AH systems anymore.
This change conditionalizes the RPM we use during the `rpm_install`
role.  On Fedora, I chose the current stable version of `ltrace` and
stuck with `epel-release` for everything else.

i-s-t: use diff RPM for 'rpm_install' on Fedora

---

docs/howto_contribute.md
roles/atomic_images_delete_all/tasks/main.yml
roles/atomic_pull/tasks/main.yml
roles/docker_build_httpd/tasks/main.yml
roles/docker_pull_base_image/tasks/main.yml
roles/docker_remove_all/tasks/main.yml
roles/docker_rm_httpd_container/tasks/main.yml
roles/docker_rmi_httpd_image/tasks/main.yml
roles/docker_run_httpd/tasks/main.yml
roles/docker_storage_verify/tasks/main.yml
roles/kubernetes_setup/tasks/main.yml
roles/rpm_ostree_install_verify/tasks/main.yml
roles/rpm_ostree_uninstall_verify/tasks/main.yml
roles/rpmdb_verify/tasks/main.yml
roles/selinux_verify/tasks/main.yml
tests/pkg-layering/main.yml
tests/pkg-layering/verify_package_deployed.yml
tests/pkg-layering/verify_package_not_deployed.yml
tests/rpm-ostree/main.yml

I've observed warnings thrown by Ansible about using Jinja2 templating
in `when:` and `failed_when:` statements like this:
```
when: "'{{ foo }}' in bar.stdout"
```
The correct way to write this is like so:
```
when: foo in bar.stdout
```
This change corrects (most) of the instances of this to the correct
format.

tree-wide: correct use of Jinja2 templating in when: statements

---

roles/selinux_verify/tasks/main.yml

Previously, the `selinux_verify` role would fail with a generic
message about finding a file or process that had an incorrect SELinux
label.  This caused additional work for anyone doing triage of the
tests and made folks unhappy.
This change alters how the role reports any instances of incorrect
SELinux labels.  The files/directories/processes are saved into a list
which can then be read out later as part of a failure message.
This should result in last failure message to include the relevant
details of the files/processes and negate the need to dig through the
logs further during triage.
Closes #260

selinux_verify: log any files/procs with incorrect SELinux labels

---

roles/selinux_verify/vars/centosdev-7.yml

We had to revert the version of `docker` on CAHC to an older version
being served up by CentOS-extras, which neccessitated the need to
update the files and processes we check for incorrect SELinux labels.
Related:  CentOS/sig-atomic-buildscripts#308

selinux_verify: update the files/procs to check for CAHC

---

roles/redhat_subscription/tasks/main.yml
roles/redhat_unsubscribe/tasks/main.yml

Our internal jobs hit some network timeouts while doing an
'unsubscribe' with `subscription-manager`.  We already had some
retries for `redhat_subscription`, but were lacking them on the
`redhat_unsubscribe`.  This change implements the retries for
'unsubscribe' and bumps up the retries on 'subscription'

roles: adjust retries on 'redhat_subscription' and 'redhat_unsubscribe'

---

.papr.yml

F27 has been released, so let's enable our CI on that image and switch
the containers to F27, too.

papr: changes related to f27 release

---

README.md

We will soon have test results for the
`fedora/27/x86_64/updates/atomic-host` ref, so update our dashboard
with the necessary info.
Additionally, I cleaned up the 'supported tests' section.

README: updates for f27, etc

---

.papr.yml
.test_director

Resolves issue #262.  The latest version of Ansible was being installed
by PAPR but A-H-T currently supports 2.2.x.  Use virtualenv to install
the supported version of Ansible for A-H-T.

Use virtualenv for PAPR

---

roles/rpm_ostree_install_verify/tasks/main.yml
roles/rpm_ostree_livefs/meta/main.yml
roles/rpm_ostree_livefs/tasks/main.yml
roles/rpm_ostree_rollback/meta/main.yml
roles/rpm_ostree_uninstall_verify/tasks/main.yml
tests/rpm-ostree/README.md
tests/rpm-ostree/info.txt
tests/rpm-ostree/main.yml

This commit adds a simple livefs test using package layering as the
change in the filesystem.
The rpm_ostree_install_verify and rpm_ostree_uninstall_verify roles
needed an option to skip the rpm-ostree status since the output is
changed with the livefs implementation. The roles were also cleaned
up and now uses the new variables from the rpm_ostree_status role.

Add test for livefs

---

roles/atomic_system_install/tasks/main.yml
tests/system-containers/main.yml

Well, we're still using `fedora/26/atomic` in our CI checks and the
version of `atomic` there is friggin old.  How old?  So old that it
will try to land an RPM on the host when you do an 'atomic install
--system' by default.
This tries to work around this problem by doing a version check and
altering how the `atomic install` command is used depending on the
version detected.

tests: handle 'atomic install --system' on old versions

---

roles/atomic_installation_verify/tasks/main.yml
roles/etcd_sys_container_install/tasks/main.yml
tests/system-containers/main.yml

Fedora 25 will be EOL shortly, so let's bump up to Fedora 26.  (I
would use Fedora 27, but not all of the old images got rebuilt, AFAIK)

stop using Fedora 25 images in roles/tests

---

roles/atomic_host_status_verify/tasks/main.yml
roles/atomic_images_list_verify/tasks/main.yml
roles/atomic_pull_verify/tasks/main.yml
roles/atomic_run_verify/tasks/main.yml
roles/atomic_scan_verify/tasks/main.yml
roles/atomic_stop_verify/tasks/main.yml
roles/atomic_system_install_verify/tasks/main.yml
roles/docker_latest_setup/tasks/main.yml
roles/docker_pull_base_image/tasks/main.yml
roles/docker_rm_httpd_container/tasks/main.yml
roles/docker_rmi_httpd_image/tasks/main.yml
roles/docker_run_httpd/tasks/main.yml
roles/docker_version_check/tasks/main.yml
roles/etc_verify_changes/tasks/main.yml
roles/ostree_admin_unlock/tasks/main.yml
roles/rpm_ostree_install_verify/tasks/main.yml
roles/rpm_ostree_uninstall_verify/tasks/main.yml
roles/rpm_signature_verify/tasks/main.yml
roles/runc_version_check/tasks/main.yml
roles/semanage_fcontext_verify/tasks/main.yml
roles/tmp_check_perms/tasks/main.yml
roles/var_files_present/tasks/main.yml

Sometimes its not easy to figure out why a test failed based on
the error message.  Digging into the code to find the failure
comparison that caused the failure is required.
Lets make the error messages more detailed when comparisons are
made so triaging failures is easier.
Note: This commit is only improving the error messages in the roles.

Improve error messages in roles

---

roles/atomic_install_version_check/meta/main.yml
roles/atomic_install_version_check/tasks/main.yml
roles/atomic_system_install/meta/main.yml
roles/atomic_system_install/tasks/main.yml
roles/etcd_sys_container_install/meta/main.yml
roles/etcd_sys_container_install/tasks/main.yml
tests/system-containers/main.yml

I was about to add a 3rd copy of the same code to detect which version
of `atomic` we are using when we run the tests.  But I came to my
senses and added a new role that handles all that.
The `atomic_install_version_check` role does a version check and sets
up a variable to use `atomic install`.  This is a follow-on (and
improvement, IMO) to #284.

add 'atomic_install_version_check' role

---

tests/admin-unlock/main.yml
tests/docker-swarm/main.yml
tests/pkg-layering/main.yml
tests/rpm-ostree/main.yml
tests/system-containers/main.yml
tests/unique-machine-id/main.yml

This is the follow on to #288 to address #239.  #288 addressed the
error messages in the roles and this commit addresses the error
messages in the tests themselves.

Improve error messages in tests

---

.papr.yml

We need `rsync` to be present on the host/container running the
Ansible tests.

papr: install rsync

---

tests/docker-build-httpd/main.yml

When running an OpenStack environment, the host under test might end
up with an MTU that doesn't jive with the Docker daemon (usually when
the MTU is lower than 1500).  This can lead to network issues when
doing `docker build`.  So we'll just set the MTU for the Docker
daemon to the same.

docker-build-httpd:  set MTU equal to default interface

---

.gitignore

When running tests locally, we can start accumulating tests artifacts
that clutter up the output of `git status`, so let's start excluding
some of them.

gitignore: add test artifacts to ignore list

---

roles/selinux_verify/vars/common.yml

When testing against systems that have slower CPUs or slower network
links, I was encountering a situation where I was not able to get the
SELinux label of the `rpm-ostree` daemon after using `rpm-ostree
status`.  I believe this was happening because the tests check the
SELinux label of `NetworkManager` first, allowing the `rpm-ostree`
process to spin down before we could check the label. (The daemon
appears to be activated via DBus (I think?), so it does not show
up in the running process list all the time.)
This change just puts `rpm-ostreed` at the top of the list so that it
is checked first.

selinux_verify: adjust order of processes to be checked

---

roles/user_del/meta/main.yml
roles/user_del/tasks/main.yml
tests/improved-sanity-test/main.yml

This adds a role named `user_del` which will delete any users (with
prejudice!) passed as a list to the role.
The `improved-sanity-test` makes use of this new role at the very end
of the test and additionally calls `docker_remove_all` to cleanup any
docker artifacts (containers/images).

test/i-s-t:  improve cleanup at end of test

---

tools/README.md

This will be used as part of the Docker Hub automated build process,
rather than the README which is in the root of the repo.
See https://hub.docker.com/r/miabbott/aht-tools/

tools: add a README file for the tools container

---

roles/atomic_images_delete_all/tasks/main.yml

The atomic_images_delete_all role was failing because the atomic
images delete command cannot delete an image if it is used in
an exited container.  The --force option is used to work around
this.

Use force option for atomic images delete all

---

tests/admin-unlock/main.yml
tests/atomic/main.yml
tests/docker-build-httpd/main.yml
tests/docker-swarm/main.yml
tests/docker/main.yml
tests/images_cve_scanner/main.yml
tests/improved-sanity-test/main.yml
tests/k8-cluster/main.yml
tests/openshift-ansible-test/main.yml
tests/pkg-layering/main.yml
tests/rpm-ostree/main.yml
tests/system-containers/main.yml
tests/unique-machine-id/main.yml

This commit fixes minor issues in the atomic host tests to comply
to the YAML spec.  The issues fixed were found using yamllint.
There were some instances of line length that could not be fixed
(i.e. Ansible when statements like  "'foo' in bar"). Using > or |
would break the logic so the line length had to be preserved.

Comply to YAML spec where possible

---

tests/admin-unlock/main.yml

Addresses #317 .  Retries were added to increase reliability of tests
when performing network operations, however, we should not retry
when we expect a failure.
I also added a minor fix to only fail when the command succeeds.

Don't retry when expecting failures

---

roles/docker_private_registry/tasks/main.yml

As noted in CentOS/sig-atomic-buildscripts#316, the downstream CentOS
Atomic Host and CAHC composes are missing the `atomic-registries`
package.  This is critical for the configuration of insecure
registries, as is necessary when setting up a registry in a container.
This works around the missing package by using package layering to
install the missing package, then proceeding with the remainder of the
role.
Closes #316

docker_private_registry: workaround missing atomic-registries

---

roles/docker_build_tag_push/files/centos/web/action
roles/docker_build_tag_push/files/fedora/web/action
roles/docker_build_tag_push/files/rhel7/web/action

Closing the mysqldb connection inside the with statement block was
causing segmentation faults and tracebacks in newer versions of
python.  This caused errors getting the action page from Apache.
Moving the connection close outside the with statement fixed this
on fedora, rhel, and centos.

Fix action script

---

roles/journal_fatal_msgs/meta/main.yml

In RHBZ#1536690, I observed there were SELinux denials present on the
host, but our tests were catching them.  These denial messages were on
the 'kernel' transport and we were only checking the 'audit' transport,
so I've added a new rule to look for denials from that 'kernel'
transport.

journal_fatal_msgs: add check for SELinux denials from kernel

---

roles/journal_fatal_msgs/meta/main.yml

We have no way to skip the check for the individual 'fatal' messages
that are covered by the `journal_fatal_msgs` role.  By adding tags to
each message we are looking for, we can selectively disable the check
for individual messages that we know still exist and allow us to
execute the remaining playbook.

journal_fatal_msgs: add tags for each fatal message

---

roles/booted_deployment_set_fact/meta/main.yml
roles/booted_deployment_set_fact/tasks/main.yml

Similar to the `rpm_ostree_status` role, when we output the status in
JSON format, one of the keys has a list of all the packages that are
included in the ostree commit.  In f6a7086, we introduced the use of a
tools container to pipe the JSON output through `jq` to hide the noisy
keys.  This is basically the same implementation.
(We probably should consolidate the two roles, but that is for another
PR...)

bdsf: utilize the tools container to hide noisy JSON keys

---

roles/resize_lv/meta/main.yml
roles/resize_lv/tasks/main.yml

We may want to resize a logical volume during our tests, in order to
make room for `ostree` host content or system container content.  This
role provides simple functionality to do so.

roles: new resize_lv role

---

roles/selinux_verify/tasks/main.yml

The `selinux_verify` role performs multiple checks of files and
processes on the host to make sure all the SELinux labels are
correct.  However, if we wanted to exclude a particular part of the
role (because of known issues), we would have to exclude the entire
role.
This change introduces a set of tags assigned to different tasks in
the role, so that we are able to selectively choose which checks
should run as part of the role.

selinux_verify: add tags for each label check

---

roles/k8_cluster_services_rc_setup/meta/main.yml
roles/k8_cluster_services_rc_setup/tasks/main.yml
roles/k8_remove_all/meta/main.yml
roles/k8_remove_all/tasks/main.yml
roles/kubernetes_set_facts/meta/main.yml
roles/kubernetes_set_facts/tasks/main.yml
roles/kubernetes_setup/meta/main.yml
roles/kubernetes_setup/tasks/main.yml
roles/rpm_version/tasks/version.yml
tests/k8-cluster/main.yml
tests/k8-cluster/vars.yml

In Fedora 27 Atomic Host, all of the `kubernetes` related packages
were removed from the host.  The replacement functionality is now
provided by system containers.
This set of changes reworks the `kubernetes_setup` role to utilize the
new system containers to bring up a single node cluster and then
proceed with the remaininder of the `k8s-cluster` test.
NOTE:  the system containers are only used in the case where the
`kubernetes` packages are not present on the host.  For other
platforms where they are present on the host, the original method of
using manifests continues to be used.
Many thanks to Kedar Bidarkar for starting this work!

 k8s-cluster: fix test for F27AH

---

tests/k8-cluster/main.yml

I've been seeing some failures in our internal jobs that look like the
final `curl` is timing out.  (Weird, since the connection is to
localhost...)
This adds some retries to the final check using `curl` to try to
alleviate the timeouts.

k8-cluster: add retries to final check

---

roles/atomic_images_delete_all/tasks/main.yml
roles/atomic_installation_verify/tasks/main.yml
roles/etcd_sys_container_install/tasks/main.yml
tests/atomic/vars/centos.yml
tests/atomic/vars/centosdev.yml
tests/atomic/vars/fedora.yml
tests/system-containers/main.yml

It would probably best to start using Fedora 27 containers instead of
Fedora 26.  While Fedora 26 will be 'maintained' until a month after
Fedora 28, I think we will get better support from the Fedora
community if we use the most recent release.
Additionally, I had to tweak the `atomic_images_delete_all` role to
remove any containers first before removing the images.  (This might
have been an artifact that came from re-using some test VMs, but
should be safe to do either way.)

tree: use F27 containers where possible

---

roles/atomic_pull/tasks/main.yml

Noticed that this role was missing some retry logic and since
networking can be dicey, we should have some retry logic.

atomic_pull: add retry logic for pull

---

.papr.yml

Fedora 26 is dead to me.
Remove the CI checks using a Fedora 26 host (which were always
failing on rebasing to a commit on the stable branch) and start using
the Fedora 27 Docker images.

papr: remove usage of Fedora 26

---

roles/kubernetes_set_facts/tasks/main.yml

The logic for determining the use of system containers was missing a
case when the `kubernetes-node` RPM was not installed on the host, but
the host was also not a Fedora/CentOS platform.  For example, our
internal 'autobrew' streams.
This updates the logic to handle this case.

k8s_set_facts: setup facts when kube node RPM not installed

---

.papr.yml
.test_director

The `centos/7/atomic` context has been consistently failing because
there are AVC denials from the kernel that are present in the version
of CentOS AH we are using.  This is preventing any useful CI checks
from being run on that platform.
This change introduces a simple check to the `.test_director` script to
see if any arguments were passed to the script.  This way, we are able
to skip tags we know are causing problems in our CI checks.
In order to utilize this change, I re-arranged the order of contexts
in the `.papr.yml` file in order to maintain inheritence between the
contexts and only pass in the extra args to the `centos/7/atomic`
context.

ci: enable extra args to be passed to .test_director

---

roles/firewalld_service_verify/meta/main.yml
roles/firewalld_service_verify/tasks/main.yml
tests/improved-sanity-test/main.yml

This introduces a new role which can be used to validate the
installation/configuration of the `firewalld` service.  It will
determine if the host under test should have `firewalld` installed and
how it should be configured if it is installed.
This initial attempt is very simple, but could be expanded to do more
complex checks if desired.
The role is used in the `improved-sanity-test` before the host is
upgraded and after upgrade.
Closes #315

roles: new role to validate firewalld install/config

---

roles/booted_deployment_set_fact/tasks/main.yml
roles/local_branch_setup/tasks/main.yml
roles/rpm_ostree_status/tasks/main.yml
roles/rpm_ostree_uninstall/tasks/main.yml
tests/pkg-layering/main.yml
tests/pkg-layering/verify_package_deployed.yml

We had a bunch of instances in the tree where we were doing
`rpm-ostree status --json` and then going through the motions to parse
the JSON to determine things like the booted deployment, etc.
Additionally, we were littering our test logs with the 'noisy' keys
from the JSON output that were handled in #301.
This change rips out all the invocations of `rpm-ostree status --json`
and replaces them with the usage of the `rpm_ostree_status` role.  Now
we have a consistent way of dealing with the JSON output from the
`status` command and only one place where we have to make changes if
needed.

use 'rpm_ostree_status' role for all the JSON output

---

README.md

We've enabled the testing of CentOS AH on our internal Jenkins
instance, so let's start showing some results here too.

README: add CentOS AH results

---

tools/Dockerfile
tools/README.md

For the rpm-ostree compose test, we need the ability to checkout
a git repo with the necessary files to compose a tree.  Instead of
package layering git onto the host, we can use the tools container
with git installed to clone the repo and save it to a volume mount
shared between the host and container.

Add git to tools container

---

README.md
Vagrantfile

Originally, the `improved-sanity-test` required that the host under
test was at HEAD-1 of the stream we were testing.  Thus, the
Vagrantfile had additional scripts in place to get the box to the
proper state.
We've moved away from that methodology and now we can just `vagrant
up` a box and run our tests against that host.
This change updates the Vagrantfile to be current with the streams we
are most interested in and removes the additional provisioning steps
required to get the box to HEAD-1.
Closes #241

Vagrantfile: major updates to get current with test states

---

roles/kubernetes_setup/tasks/main.yml

I'm not sure how this test was working but there are two regex
groups that were missing double quotes based on how the statements
were structured.
The first regex was a replace which ends in .*$ which will match
anything including the end quote but the replacement string did
not include the end double quote.
The second regex was a regex group capture that does not include
the end double quote so the line replacement needs to have the
double quote included.

k8-cluster: fix missing double quotes on regex

---

roles/kubernetes_set_facts/tasks/main.yml
roles/kubernetes_setup/tasks/main.yml
roles/rpm_ostree_install/tasks/main.yml
tests/k8-cluster/main.yml

Two major changes here:
1)  Pin the system containers to a previous version that was working
2)  Make sure that 'atomic 1.22' is installed on the host
The new requirement on 'atomic 1.22' is to resolve the following issue
with SELinux labeling - projectatomic/atomic#1185
This is only a temporary change; once the latest versions of the
system containers are known to be working, we can revert a lot of
this.

k8-cluster:  revert to using older system containers

---

roles/kubernetes_set_facts/tasks/main.yml
roles/kubernetes_setup/files/kubelet.kubeconfig
roles/kubernetes_setup/tasks/main.yml
tests/k8-cluster/main.yml

The k8-cluster test was failing in the system container use case.  The
web and db containers weren't being created because no nodes were
available.  I was able to root cause the issue to the deprecation of
the --api-servers option.  Kubernetes 1.9 uses a kubeconfig file for
the node to determine the api server.  I used a kubernetes PR [0] as
reference for the creation of the kubeconfig file and then tacked on
the --kubeconfig option to the KUBELET_ARGS.
[0] https://github.com/kubernetes/contrib/pull/2863/files

k8-cluster: use kubeconfig

---

.papr.yml

Lets not fail the CAHC CI check because a package isn't in CAHC yet.
Since this label isn't fatal to functionality, it's pretty safe
to skip this until we get an updated version of 'container-selinux'
with the neccessary fix:
https://github.com/projectatomic/container-selinux/pull/50

papr: skip default_t checks temporarily for CAHC

---

tests/system-containers/vars.yml

When a fully qualified container name is not used, skopeo will use
the default container registry and use a short shorname.  In this
case gscrivano/hello-world shows up as hello world in the atomic
images list output.  The system-container looks for the short name
that was passed in when installing the system container so the test
ends up failing.  The simple fix is to use fully qualified container
names.

system-containers: use FQ container name

---

tests/rpm-ostree/main.yml

Since the ability to create composes exists for Fedora and Centos
Atomic Host Continuous streams, we should have a test for it.
This change only includes a basic test for rpm-ostree compose.
There should be more tests to cover additional rpm-ostree compose
subcommands and options.

Add basic rpm-ostree compose test 

---

README.md

This adds a short note about packages that need to be installed ahead
of time before you can use the `virtualenv` approach for setting up
an a-h-t environment.
Closes #267

README: add notes about package requirements

---

roles/docker_storage_verify/tasks/main.yml
roles/docker_storage_verify/vars/redhat-7.5.yml

This modifies the `docker_storage_verify` role to look for the
`ansible_distribution_version` in the name of the var file.  The
RHELAH 7.5 version of said file is also added.

docker_storage_verify: add in support for rhelah 7.5

---

roles/docker_build/files/centos/systemd_httpd/Dockerfile
roles/docker_build/files/centos/systemd_httpd/makecache.sh
roles/docker_build/files/fedora/systemd_httpd/Dockerfile
roles/docker_build/files/fedora/systemd_httpd/makecache.sh
roles/docker_build/files/rhel7/systemd_httpd/Dockerfile
roles/docker_build/files/rhel7/systemd_httpd/makecache.sh
tests/improved-sanity-test/main.yml

Since it is possible to run systemd in a container without the
`--privileged` flag, we decided we should have a test for this going
forward.
This change adds in the files necessary to build an `httpd` container
that uses `systemd` as its init mechanism.  Additionally, we add the
building/running of said container to the `improved-sanity-test`.

i-s-t: add test for non-priv systemd container

---

tools/Dockerfile
tools/README.md

Install createrepo_c and python on the aht-tools container so it we
can create a local repo and serve it through python's
SimpleHTTPServer.
Also added notes in the README to explain why the packages were added.
This might help in the future to determine if a package is still
needed in the tools container.

Install rpms for rpm-ostree install gpg test

---

tests/pkg-layering/main.yml

This commit adds a gpg test for package layering.  The test uses the
aht-tools container to create a local repo with the aht-dummy rpm and
serve it through SimpleHTTPServer.  The tools container was chosen
because it was an easy way to host the repo without requiring another
system or installing packages on the host.
Addresses issue #349

Add gpg package layering test

---

roles/reboot/tasks/main.yml
tests/improved-sanity-test/main.yml

These two commits include the initial changes to try to support the [Fedora Standard Test Interface](https://fedoraproject.org/wiki/CI/Tests) and [Standard Test Roles](https://fedoraproject.org/wiki/CI/Standard_Test_Roles).
The first commit makes small changes to the `improved-sanity-test` so that it can be invoked by the Fedora STI.
The second commit changes the methodology of the `reboot` role to handle the way the STI boots up an Atomic Host as a test subject.  
There are more details in the individual commit messages and I encourage you to read them.
(I'm not 100% confident about getting these merged in, so marking it as WIP for now)

tree: initial changes to support Fedora STI/STR

---

tests/rpm-ostree/main.yml

Would have fallen over for https://bugzilla.redhat.com/show_bug.cgi?id=1571264

rpm-ostree/main: Run ostree admin status too

---

.papr.yml

We want to run the 'docker' test suite in CI with
'g_docker_latest=false' for Fedora because the `docker-latest` package
is not shipped on that distro.
Also add the 'default_t' test to the list of skipped tests for CentOS
until the new version of atomic lands.

papr: adjust which tests are skipped per platform

---

roles/booted_deployment_set_fact/tasks/main.yml

In our CI tests, it was possible for the 'sanity' test to fail when
trying to rebase to the commit stored in the `g_archive_checksum`
variable.  This can happen if the 'sanity' test was run after a test
that did package layering operations and did not clean up after
itself.  This would cause the value of `checksum` in `rpm-ostree
status` to point to the current commit with the packages layered.
Since we only use `g_archive_checksum` as a way to rebase the host,
the rebase operation would fail because the commit with the package(s)
layered would not exist on the remote.
This solution is to look for the `base-checksum` key in the JSON of the
`booted` deployment and use that if it exists, otherwise fallback to
just using `checksum`.

bdsf/main: use 'base-checksum' if available

---

tests/atomic/main.yml

The test was sloppy about cleaning up after itself, in that it did no
cleanup at all really.  This adds a final playbook that will cleanup
the containers/images and rollback any layering of 'atomic-registries'
package that might have occurred.

atomic/main: cleanup after the tests are done

---

requirements.txt

If there is an existing Python environment where Ansible 2.2 was
previously installed (as required previously), the `ansible<2.5`
requirement would be satisfied and would not get upgraded to Ansible
2.4 as we desire.  This updates the `requirements.txt` to require
something greater than 2.3 but less than 2.5.

requirements: dial in to Ansible 2.4

---

roles/reboot/tasks/main.yml

In RHBZ#1572944 it is speculated that /dev/random is taking a longer
amount of time to initialize with entropy in newer Linux kernels.
The observable result of this is that boot times are increased, to the
tune of 3-4m.  Perhaps I'm being overzealous with the 300s timeout,
but we don't have much to lose at this point.
h/t to @jlebon for the probable root cause in projectatomic/papr#97

reboot/main: increase default timeout

---

roles/rpm_ostree_rebase/tasks/main.yml
tests/improved-sanity-test/main.yml
tests/rpm-ostree/main.yml

There are two issues encountered after the Ansible 2.4 change.  The
first issue is the rpm_ostree_rebase role.  The refspec variable
inside the role seems to get populated with refspec somewhere up
before the rebase call and causes a failure.  This was fixed by using
a prefixed variable name (ror_refpsec) which is a best practice
anyhow.
The second issue is a little more interesting.  After calling the same
role (rpm_ostree_install_verify) multiple times in the rpm-ostree test,
the import_role doesn't seem to be respecting the variable that is
being passed in.  Instead it is using a value from somewhere up before
the same role is called.  This leads to the conclusion that prefix in
the rebase variable name above may not work in all cases.  This was
fixed by using an include_role which is …

Resolve Ansible 2.4  import_role variable issue

---

roles/journal_fatal_msgs/meta/main.yml
roles/journal_search/tasks/main.yml
roles/journal_search/templates/journal_found.j2
roles/selinux_verify/tasks/main.yml
roles/selinux_verify/templates/selinux_verify.j2

A common problem when runing the 'sanity' test is that it can fail
very early because a stream has an SELinux denial immediately upon
booting the host.  While it is helpful to detect this kind of denial,
failing the whole test suite near the beginning could let other
problems slip by.
This change attempts to avoid the 'early failure' scenario by
capturing the various SELinux failures and dumping them to files on
the host where the playbook is running.  I'm open to changing how the
files are named or what not.
I've made a few assumptions about how this works because we are
basically the only ones using these roles/tests.  To everyone else,
YMMV.

roles: don't fail on SELinux failures; record them to files

---

.papr.yml

Let's start testing the tests against F28 and switch to using the
'updates' stream on Fedora 27 AH.

papr:  update for release of F28

---

tests/admin-unlock/add_remove_package_non_persistence.yml
tests/admin-unlock/add_remove_package_persistence.yml
tests/admin-unlock/cleanup.yml
tests/admin-unlock/hotfix_rollback.yml
tests/admin-unlock/main.yml
tests/admin-unlock/no_install_without_unlock.yml
tests/admin-unlock/setup.yml
tests/admin-unlock/unlock_twice_error.yml
tests/admin-unlock/unlock_twice_hotfix_error.yml

Instead of failing early (the default behavior for Ansible), this PR
uses Ansible's block/rescue to catch errors and continue execution.
There are a few major changes in the structure of the test.
- Each tests is broken into individual yaml files as set of tasks
- Each test that will continue on failure is added as an include_task
in the main.yml file in a block/rescue.
- Each test that we want to fail fatally will not be in a block/rescue
- Each test will capture the result and result details in a list of
dictionaries that can be evaluated at the end of the main.yml test
- When an exception is caught in a block/rescue the failed task
details is stored in ansible_failed_task and ansible_failed_result
The goal was to organize the tests better simplify adding new tests to
the test suite. …

admin-unlock: continue to run on failure

---

tests/admin-unlock/main.yml

The way it was previously written, the log file would only be written
if there was a failure during the cleanup.  We want to write the file
when the cleanup fails or passes.  Basically use the always clause.

admin-unlock: always save log

---

tests/improved-sanity-test/main.yml

Otherwise we don't have access to the registry anyway.

ist: only run OpenSCAP test on RHEL

---

tests/docker/cleanup.yml
tests/docker/functional.yml
tests/docker/main.yml
tests/docker/setup.yml

This doesn't really continue on failure because there is only one main
test but the logic is there to add more tests in.  This is a
continuation of #391 for the docker test suite.

docker: continue on failure

---

tests/atomic/cleanup.yml
tests/atomic/fully_qualified_container_name.yml
tests/atomic/fully_qualified_name.yml
tests/atomic/images_update.yml
tests/atomic/main.yml
tests/atomic/pull_digest.yml
tests/atomic/pull_storage.yml
tests/atomic/pull_tags.yml
tests/atomic/setup.yml
tests/atomic/short_name.yml

This is a follow-on to #391 for the atomic test suite.  The changes
allow the tests to continue to run on failure using Ansible's
block/rescue/always.

atomic: continue to run on failure

---

tests/docker-swarm/cleanup.yml
tests/docker-swarm/functional.yml
tests/docker-swarm/main.yml
tests/docker-swarm/setup.yml

This is a continuation of the continue on failure effort using
block/rescue/always for the docker-swarm test suite.  There is only
one test so it really doesn't really change anything but the logic is
there to add more tests.

docker-swarm: continue on failure

---

roles/docker_storage_verify/vars/redhat-3.yml
roles/rpm_ostree_rebase/tasks/main.yml
roles/selinux_verify/vars/redhat-3.yml
tests/improved-sanity-test/README.md
tests/improved-sanity-test/main.yml

Lets add tagging to the improved-sanity-test to run against RHCOS.
There is an existing cloud_image tag to run against cloud images so
using tag `rhcos` to run against RHCOS seemed like a good idea.  The
roles without tags did not work with RHCOS so it will only test a
subset of the original improved-sanity-test.
Since RHCOS shares the same ansible_distribution as RHEL AH, I had to
use the ansible_distribution_major version to distinguish between
RHCOS and RHELAH in docker_storage_verify and selinux_verify.
Also snuck in a small fix for the rpm_ostree_rebase role.

I-S-T: Add support for running against RHCOS

---

tests/system-containers/cleanup.yml
tests/system-containers/flannel_etcd.yml
tests/system-containers/install_uninstall.yml
tests/system-containers/main.yml
tests/system-containers/negative.yml
tests/system-containers/pass_variables.yml
tests/system-containers/reboot.yml
tests/system-containers/rootfs.yml
tests/system-containers/run_state_dir.yml
tests/system-containers/setup.yml
tests/system-containers/update_rollback.yml

This updates the `system-containers` suite to use the
'continue-on-failure` model that has been used for other test suites.

system-containers: use continue-on-failure model

---

roles/rpm_ostree_status/tasks/main.yml

When reusing a test system to validate some other changes, I noticed
that there were a pile of `aht-tools` containers on the host.  This
looks like an oversight when I first started using the tools container
to filter out JSON keys; should make things a little more tidy.

roles/rpm_ostree_status: remove tools container on exit

---

tests/docker-swarm/main.yml

I don't think Ansible considers handled exceptions as failures even
though it will display failures in the playbook summary.  Lets
explicitly fail if any of the test results have failures.

docker-swarm: explicitly fail based on test results

---

.gitignore
roles/ostree_admin_status/meta/main.yml
roles/ostree_admin_status/tasks/main.yml
tests/improved-sanity-test/main.yml
tests/rpm-ostree/cleanup.yml
tests/rpm-ostree/cleanup_pending.yml
tests/rpm-ostree/compose.yml
tests/rpm-ostree/deploy_commit.yml
tests/rpm-ostree/deploy_version.yml
tests/rpm-ostree/initramfs.yml
tests/rpm-ostree/livefs.yml
tests/rpm-ostree/main.yml
tests/rpm-ostree/negative.yml
tests/rpm-ostree/override_remove_reset.yml
tests/rpm-ostree/override_replace_reset.yml
tests/rpm-ostree/setup.yml
tests/rpm-ostree/upgrade_rebase.yml
tests/rpm-ostree/upgrade_rebase_install_uninstall.yml

This adapts the `rpm-ostree` test suite to the continue on failure model.  As part of the work, I made some slight changes to the 'compose' portion of the test suite to make it a bit more resilient.
Additionally, I snuck in a change to the `.gitignore` file to ignore the `.log` files that are being generated.
Partially addresses #375

Adapt the 'rpm-ostree' test suite to continue on failure

---

tests/system-containers/main.yml

Ansible doesn't seem to fail on handled exceptions so lets explicitly
fail based on the test results.

system-containers: explicitly fail on results

---

tests/docker/main.yml

Ansible does not consider handled exceptions failures and will return
0.  Lets explicitly fail the playbook based on test results so Ansible
will return non-zero.

docker: explicitly fail on test results

---

tests/admin-unlock/main.yml

Ansible does not consider handled exceptions failures and will return
0.  Lets explicitly fail the playbook based on test results so Ansible
will return non-zero.

admin-unlock: explicitly fail on test results

---

tests/atomic/main.yml

Ansible does not consider handled exceptions failures and will return
0.  Lets explicitly fail the playbook based on test results so Ansible
will return non-zero.

atomic: explicitly fail on test results

---

tests/pkg-layering/main.yml

Ansible does not considered handled exceptions failures.  Lets
explicitly fail based on test results.

package-layering: explicitly fail on test results

---

tests/k8-cluster/main.yml

I don't think Ansible considers handled exceptions as failures even
though it will display failures in the playbook summary. Lets
explicitly fail if any of the test results have failures.

k8-cluster: explicitly fail based on test results

---

roles/docker_pull_run_remove/tasks/main.yml
roles/docker_pull_run_remove/vars/main.yml

This changes the `docker_pull_run_remove` role to add a test for the
use of `--cpu-shares` flag when doing `docker run`.  This is to catch
regressions such as RHBZ#1585735.
Additionally, I expanded the list of images we are testing to include
images from registries other than docker.io.
Closes #414

docker_pull_run_remove: add test for cpu-shares flag

---

roles/docker_pull_run_remove/tasks/main.yml
roles/docker_pull_run_remove/vars/main.yml

The `name` of the first task in this role wasn't accurate once we
started pulling more images from other registries.  This makes the
language a bit more generic.
Additionally, the r.c.o/centos image recently started to fail and this
was causing all the sanity tests to fail.  Switch the image to use
r.c.o/centos/centos as a hotfix.

dprr: Clean up language and hotfix the centos image

---

roles/docker_pull_run_remove/tasks/main.yml
roles/docker_pull_run_remove/vars/main.yml

The i-s-t has been failing for longer than I would care to admit
because of CentOS/sig-atomic-buildscripts#329 and there's been little
movement in the direction of fixing that.  So we'll workaround the
deficincieny by using two lists of images, one that works for CentOS
derived streams and another that works for the rest.

dprr: modify list of "popular" images for CentOS based streams

---

roles/docker_storage_verify/tasks/main.yml
roles/docker_storage_verify/vars/centos-7.yml
roles/docker_storage_verify/vars/centos.yml
roles/docker_storage_verify/vars/centosdev-7.yml
roles/docker_storage_verify/vars/devicemapper.yml
roles/docker_storage_verify/vars/fedora-26.yml
roles/docker_storage_verify/vars/fedora-27.yml
roles/docker_storage_verify/vars/fedora-28.yml
roles/docker_storage_verify/vars/fedora-29.yml
roles/docker_storage_verify/vars/overlay2.yml
roles/docker_storage_verify/vars/redhat-3.yml
roles/docker_storage_verify/vars/redhat-7.5.yml
roles/docker_storage_verify/vars/redhat-7.yml
roles/docker_storage_verify/vars/redhat.yml

Almost all of the streams are using `overlay2` as the docker storage
driver now, so we can remove a lot of the conditional workarounds we
had.
If we can get CAHC to switch to `overlay2` (see
CentOS/sig-atomic-buildscripts#341), we can simplify this role even
more.

dsv: update role to be more consistent across all streams

---

roles/firewalld_service_verify/tasks/main.yml

All of the Atomic Host streams should now have `firewalld` installed,
so let's remove the conditionals and always check that it is there.

fsv: always check for the presence/usage of firewalld

---

tests/improved-sanity-test/main.yml

Lets remove the rhcos tag from the firewalld role because rhcos does
not have firewalld.

i-s-t: remove rhcos tag from firewalld check

---

tests/rpm-ostree/initramfs.yml

The BootLoaderSpec filename change in ostree [0] is causing failures
in streams containing the change.  This commit will handle pre and
post BLS filename changes using a simple regex.
[0] https://github.com/ostreedev/ostree/pull/1654

initramfs: update test for BootLoaderSpec change

---

tests/improved-sanity-test/main.yml

CentOS Atomic Host and CAHC inherited the systemd container cgroups
issue and now needs the container_manage_cgroup seboolean.

i-s-t: set container_manage_cgroup for all streams

---

roles/atomic_installation_verify/tasks/main.yml

CentOS AH has an old version of atomic which is fixed upstream [0]
which causes the uninstall of cockpit to fail if a name is not passed
in.  This commit works around it until CentOS Atomic Host is updated.
[0] https://github.com/projectatomic/atomic/issues/1219

auv: use container name in uninstall

---

.papr.yml
roles/atomic_installation_verify/tasks/main.yml

The `atomic` command is fixed across all the streams, so we can
stop using the workarounds.

stop using workarounds for `atomic` command

---

roles/atomic_installation_verify/tasks/main.yml

On RHELAH, it seems that you need to pass the name of the container
when using `atomic uninstall` if `atomic install` has been used
multiple times.  (This only seems to bite me when I'm reusing a host
for multiple rounds of tests and the host is not "clean".  The
automated jobs appear to avoid this condition.)

aiv: use name when uninstalling container

---

.papr.yml

I switched to using F28 containers, too

papr: remove F27; add F29

---

.papr.yml
roles/handler_notify_on_failure/handlers/main.yml

This can be help when an error in a current boot happens because of
something that happened in the *previous* boot. There doesn't seem to be
a concise way to tell `journalctl` to list both the current and previous
boots but not the ones before that, so we just append to the tmpfile in
a second invocation.

handler: also save journal of previous boot

---

tests/pkg-layering/install_invalid_pkg.yml

The error message changed for installing invalid packages.  Update the
test so it doesn't fail.

pkg-layering: update error message check

---

tests/pkg-layering/install_existing_pkg.yml

In newer versions of rpm-ostree package layering, the user has to
utilize the --allow-inactive option to explicitly require an existing
package.  This PR handles this behavior and older behavior for lagging
streams.

pkg-layering: handle allow-inactive option

---

roles/rpm_ostree_uninstall_verify/tasks/main.yml
tests/rpm-ostree/override_remove_reset.yml

We have been sporadically hitting an issue with Ansible where the
arguments passed in are not overwriting the previous values for those
variables.  This may be an Ansible bug [0].
The only way we have been able to mitigate this is by using
include_role instead of import role.  So why not use include_role
everywhere?  Ansible has a recursion depth limit that is hit when
include_role is used often.
Another change that was needed was to make the binary check optional
since some RPMs don't exactly have a binary that can be checked with
command -v.
[0] https://github.com/ansible/ansible/issues/37787

rpm-ostree: workaround ansible variable issue

---

tests/atomic/vars/fedora.yml

The newer version of atomic now pulls cockpit/ws from
registry.centos.org/cockpit/ws instead of docker.io/cockpit/ws

atomic: use centos registry for fq name

---

roles/podman_pull_run_remove/meta/main.yml
roles/podman_pull_run_remove/tasks/main.yml
roles/podman_pull_run_remove/vars/main.yml
tests/improved-sanity-test/main.yml

`podman` is included in most (all?) of the AH streams that we are testing, so let's start making sure it works on Atomic Host.
This is a re-implementation of the `docker_pull_run_remove` role that uses `podman`.  It's slightly more comprehensive than the original role, but still very bare bones.
Closes #378

introduce podman sanity checks

---

tests/pkg-layering/install_invalid_pkg.yml

Some of the streams are still using older versions of rpm-ostree that
doesn't have the newer error message.

pkg-layering: account for different error messages

---

roles/docker_pull_run_remove/tasks/main.yml
roles/podman_pull_run_remove/tasks/main.yml

We haven't been testing the `docker/podman exec` path and missed the
following regressions in RHELAH:
https://bugzilla.redhat.com/show_bug.cgi?id=1650512
https://bugzilla.redhat.com/show_bug.cgi?id=1655214
This adds a simple test for both.

roles: add regression tests for docker/podman exec

---

tests/atomic/short_name.yml

The image cockpit/ws matches images in docker.io and
registry.centos.org.  When pulling with short name, it is not
predictable which registry atomic will pull from.  This change is a
bit of a hack to force atomic to pull from registry.centos.org.

atomic: handle multiple registries shortname pull

---

roles/rpm_ostree_reset/meta/main.yml
roles/rpm_ostree_reset/tasks/main.yml
tests/rpm-ostree/livefs.yml

Livefs has been reworked and the deployments after rebooting from
livefs has changed to only contain the livefs deployment and the
finalized staged deployment.  The original deployment (pre-layering
and livefs) will no longer be in the deployment list.

livefs: adapt test to new behavior

---

roles/user_verify_missing/tasks/main.yml
roles/user_verify_present/tasks/main.yml

It looks like projectatomic/rpm-ostree#1726 changed how `useradd`
operates on `ostree` hosts, so we have to look for `/var/home/<user>`
now.  Except that not all the `ostree` hosts will have this change, so
make it an optional part of the regex pattern.

roles/user_verify*: change grep pattern for home dir change

---

tests/rpm-ostree/vars.yml

The Fedora 27 tzdata package location no longer exists so use the
Fedora 29 tzdata package instead.

rpm-ostree: update tzdata package

---

tests/system-containers/vars.yml

The original hello-world image broke so a new image was built with
the original Dockerfile and uploaded to docker hub.  This file
should be used going forward.

system-containers: update hello-world image

---

roles/selinux_verify/vars/redhat-7.7.yml

`docker_latest` will be removed in RHELAH 7.7, so let's not go looking
for files related to it.
Also made a small change to the list of files for the RHELAH previous
to 7.7...forgot `docker-init-current` for all these years, but might
as well fix it.

roles/selinux_verify: support RHELAH 7.7

---

tests/admin-unlock/vars.yml

The `fpaste` package requires python3 now and is causing the admin
unlock test to fail.  Switch to `htop` package to avoid this error.

admin-unlock: use package that does not require python3

---

tests/rpm-ostree/vars.yml

Update to the new location of the tzdata package because the old
one is no longer there.

rpm-ostree: update tz data package location

---

tests/rpm-ostree/vars.yml

The rpm-ostree test was failing because the format of the rpm in
Fedora 31 was incompatible with RHEL.  Switch to the Fedora 30
tzdata package.

rpm-ostree: replace f31 with f30 tzdata package

---

roles/podman_pull_run_remove/tasks/main.yml

"Couldn't resolve host name" error is showing up while installing
packages via dnf in Fedora 35 container images.
There is a clone3 incompatibility and podman needs to run with
seccomp=unconfined
See https://bugzilla.redhat.com/show_bug.cgi?id=1985499

podman needs seccomp=unconfined for newer images

---

tests/docker-swarm/vars.yml

The docker.io/httpd image has changed and will not start automatically
anymore.  Change it to another httpd image that comes from quay.io.

docker-swarm: change httpd image
