projectatomic/atomic-host-tests

rhel/subscription_data.csv.sample, tests/new-image-smoketest/README.md, tests/new-image-smoketest/main.yaml, tests/new-tree-smoketest/README.md, tests/new-tree-smoketest/main.yaml
`rhel/subscription_data.csv.sample`
- Sample subscription data with dummy values
`tests/new-image-smoketest/README.md`
- New README about the test
`tests/new-image-smoketest/main.yaml`
`tests/new-tree-smoketest/README.md`
`tests/new-tree-smoketest/main.yaml`
- Update information about how variables are included
=> Improve documentation

tests/improved-sanity-test/info.txt
This is a basic text file with summary of tests in playbook.  It will help users understand what the playbook does and will also be used in CI notifications.
=> Adding info.txt which has the description of the tests that are run

roles/docker_build_httpd/files/rhel7_httpd_Dockerfile
Remove some tabs in the Dockerfile which made the alignment off
compared to the rest of the file.
=> docker_build_httpd: clean up tabs

Vagrantfile
This removes the F23 testing option, adds the F25 testing option, and
changes CAHC to pull the Vagrant box from the ci.centos.org location.
=> Vagrantfile: add F25, remove F23, update CAHC

roles/semanage_add_verify/tasks/main.yml, tests/improved-sanity-test/main.yml
Test to make sure that policies can be added to set selinux context
of files within a directory.
A regression test for BZ1398427.
=> Add semanage add test

callback_plugins/default.py
There was a particular failure that caused the failure details to not
be displayed in the output of playbook test run.  Upon debugging, it
was discovered that the callback plugin was using code from Ansible 2.2.x,
which referenced a private member variable in the constructor that does
not exist in Ansible 2.1.  The code is now replaced with the default
Ansible 2.1.x code.
Having the play name  that the failed task occurred in was still needed
so I created a private variable that gets set when a new play starts.
=> Fix blank failure output

tests/docker/main.yml, tests/improved-sanity-test/main.yml
This change just reflows some of the uses of `role:` to match the
style we have used elsewhere.  I think this covers all the 'bad' style
uses.
=> tests: update for consistent code style

roles/atomic_installation_verify/tasks/main.yml, roles/docker_build_tag_push/tasks/main.yml, tests/docker/README.md, tests/pkg-layering/main.yml, tests/runc/main.yml
While re-testing the various playbooks after I had cleaned up the
repo, I found a few places where our conditionals were incorrect.
This fixes these errors and sneaks in a typo fix as well.
NB: this is the last of three commits that cleanup the repo.  The
other two commits should be merged first before we get to this one.
=> Correct some conditional statements

roles/selinux_verify/vars/fedora-26.yml
I missed some files that should be checked in #138; this just adds
those files to the list.
=> roles: add additional checked files for F26

README.md
Add more documentation on the custom log features of atomic host
tests.
=> Add documentation for logging features

.gitignore
Signed-off-by: Chris Evich <cevich@redhat.com>
=> Ignore compiled python and vim swap files

CONTRIBUTING.md
Added a section on submitting issues and some more details about
submitting PRs.
=> CONTRIBUTING: expand on issues and PRs

roles/docker_storage_verify/tasks/main.yml, roles/docker_storage_verify/vars/centos-7.yml, roles/docker_storage_verify/vars/centos.yml, roles/docker_storage_verify/vars/centosdev-7.yml, roles/docker_storage_verify/vars/devicemapper.yml, roles/docker_storage_verify/vars/fedora-24.yml, roles/docker_storage_verify/vars/fedora-25.yml, roles/docker_storage_verify/vars/fedora-26.yml, roles/docker_storage_verify/vars/fedora-27.yml, roles/docker_storage_verify/vars/overlay2.yml, roles/docker_storage_verify/vars/redhat-7.yml, roles/docker_storage_verify/vars/redhat.yml
This role will check for the correct default Docker storage driver and
that any mounts are in place.
Closes #121, Closes #166
=> roles: add checks for Docker storage configuration

roles/docker_storage_verify/vars/fedora-28.yml
Need to add a fedora-28.yml vars file to test rawhide.
=> Add Fedora rawhide overlay2 docker storage verification

README.md
improved-sanity-tests folder doesn't exist
replace by improved-sanity-test
=> improved-sanity-test not improved-sanity-tests

.test_director, roles/kubernetes_setup/tasks/main.yml
Check syntax of playbooks as part of the PR and run process.
=> Check syntax

tests/k8-cluster/cleanup.yml, tests/k8-cluster/main.yml, tests/k8-cluster/setup.yml, tests/k8-cluster/single_node_cluster.yml
Convert the k8-cluster test to the `continue on failure.  Partially addresses
issue #375.
=> k8-cluster: continue on failure

roles/rpm_ostree_livefs/tasks/main.yml
Add the --i-like-danger flag to livefs
=> livefs: add i-like-danger flag

roles/booted_deployment_set_fact/meta/main.yml, roles/rpm_ostree_status/meta/main.yml, roles/rpm_ostree_status/tasks/main.yml, tests/docker-build-httpd/README.md, tests/docker-build-httpd/files/centos_httpd/Dockerfile, tests/docker-build-httpd/vars.yml, tests/pkg-layering/gpg.yml, tests/rpm-ostree/compose.yml, tools/README.md
We saw some rate limiting issues when pulling from docker.io, so these are some changes to help alleviate that problem in the future
=> Updates to container image registries

tests/rpm-ostree/vars.yml
Update to F32 tzdata package since F30 is EOL.
=> rpm-ostree: update tzdata package
